scripts/councils/NELincs.py
tests/input.json

Added support for NE Lincs' collection timeline view using the UPRN of a property in the URL:
https://www.nelincs.gov.uk/refuse-collection-schedule/?uprn=XXXXXXXX&view=timeline
This should resolve #41.

Added NE Lincs

---

scripts/councils/StHelensBC.py
tests/input.json

Saw a request on the [Home Assistant thread](https://community.home-assistant.io/t/bin-waste-collection/55451/374) for this council (though not GitHub issue).
This will work on properties within the St Helens Borough Council area. URL to parse is:
> https://secure.sthelens.net/website/CollectionDates.nsf/servlet.xsp/NextCollections?refid=XXXXXXXX&source=1
Of course, with the XXXXXXXX replaced by the property UPRN

Added St Helens Borough Council

---

scripts/councils/CardiffCouncil.py
tests/input.json

I've seen this one requested a couple of times. Since Cardiff Council doesn't use in-URL UPRNs, my solution here was essentially "pretend to be Chrome". So it basically gets a JWT token so it can use the council's API to make a request for the data instead. (If that approach interests anyone, please feel free to use my code later 😄)
Anyways, the UPRN needs changing on line 115 before use. It can use any URL, but the actual page one is:
> https://www.cardiff.gov.uk/ENG/resident/Rubbish-and-recycling/When-are-my-bins-collected/Pages/default.aspx
This PR also closes #13.

Add Cardiff Council

---

scripts/councils/EastDevonDC.py
tests/input.json

Saw this one requested in HA forum thread. It works with the URL:
> https://eastdevon.gov.uk/recycling-and-waste/recycling-and-waste-information/when-is-my-bin-collected/future-collections-calendar/?UPRN=XXXXXXXXX
It should support parsing for both regular and bank holiday replacement collections.

Add East Devon District Council

---

scripts/councils/WarwickDistrictCouncil.py

Use getText() for the the collection date to return the raw text instead of the beautifulsoup class as the collectionDate

Fix parse error in Warwick council

---

uk_bin_collection/tests/council_schemas/NorthLanarkshireCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/NorthLanarkshireCouncil.py

Adds North Lanarkshire Council support. Tested with multiple valid URLs from the North Lan website: https://www.northlanarkshire.gov.uk/bin-collection-dates

Adds North Lanarkshire Council (Scotland)

---

README.md

Added links to the `gh-pages` deployed assets
- [3.9](https://robbrad.github.io/UKBinCollectionData/3.9/)
- [3.8](https://robbrad.github.io/UKBinCollectionData/3.8/)

Add Reports link

---

uk_bin_collection/tests/council_schemas/EastNorthamptonshireCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/EastNorthamptonshireCouncil.json
uk_bin_collection/uk_bin_collection/councils/EastNorthamptonshireCouncil.py

Closes #2 
This was a tricky one as the dates are generated using Javascript based on the JSON response for the UPRN.
Mimicking the JS functions in Python allows us to produce the same dates.
A hash check against the council's JS file is in place as the script would still output the dates based on the old logic if their JS functions are updated otherwise.

Add support for East Northamptonshire Council

---

uk_bin_collection/tests/council_schemas/TorbayCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/TorbayCouncil.json
uk_bin_collection/uk_bin_collection/councils/TorbayCouncil.py

Add support for Torbay Council

---

uk_bin_collection/tests/council_schemas/SouthNorfolkCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/SouthNorfolkCouncil.json
uk_bin_collection/uk_bin_collection/councils/SouthNorfolkCouncil.py

Closes #37
The website didn't seem to work for any Broadland Council's postcodes, it appears the council has added a bin collection app with different APIs which may deprecate the API this parser uses in future.

Add support for South Norfolk Council

---

.github/workflows/wiki.yml

Allow wiki updates to still be deployed on commit/push failure
Ref https://github.com/robbrad/UKBinCollectionData/issues/100#issuecomment-1452608706

Wiki workflow fix to still deploy on commit/push error

---

uk_bin_collection/uk_bin_collection/common.py

All the documentation suggest to run the script from the uk_bin_collection/uk_bin_collection/ folder, but if you add -d (dev mode) to the script it will fail unless you run it from the UKBinCollectionData folder.
Steps to reproduce
Go to script folder (ie cd UKBinCollectionData/uk_bin_collection/uk_bin_collection)
Run script in dev mode (ie, python collect_data.py <council_name> "<collection_url>" -d)
Expected result
The output.json file is created
Actual result
Traceback (most recent call last): File "/Users/ryck/Projects/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 90, in <module> main(sys.argv[1:]) File "/Users/ryck/Projects/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 73, in main return client_code( File …

Expect dev mode to be run from the script folder

---

uk_bin_collection/tests/council_schemas/LisburnCastlereaghCityCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/LisburnCastlereaghCityCouncil.json
uk_bin_collection/uk_bin_collection/councils/LisburnCastlereaghCityCouncil.py

I've added a class to retrieve data for the Lisburn and Castlereagh City Council.
A bit of a weird API, but the interactive flow can be seen by going to https://lisburn.isl-fusion.com/ and entering a postcode, eg. BT26 6LR, and then selecting an address, eg. 32 Ballyworfy Rd.
This class basically replicates that flow, using requests and some parsing of the results. The API seems to return it's payloads as `application/json`, but it includes a `html` key in the JSON object, which I had to parse to match up with a house number. I use that house number of retrieve a unique identifier for an address, which can then be used to look up the bin schedule. The response for the bin schedule includes a `nextCollections` item in the JSON response, so I use that to get the next three weeks of bin …

Added Lisburn and Castlereagh City Council

---

uk_bin_collection/tests/council_schemas/WokingBoroughCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/WokingBoroughCouncil.json
uk_bin_collection/uk_bin_collection/councils/WokingBoroughCouncil.py
uk_bin_collection/uk_bin_collection/get_bin_data.py
wiki/Councils.md

Closes #263. Listed as support for Woking, but it should work for any council with waste management provided by Joint Waste Solutions as explained in the original request.
Also adds a change to pass the URL through to the scraper class (used here).

Add support for Woking Borough Council

---

uk_bin_collection/tests/council_schemas/BasingstokeCouncil.schema
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/BasingstokeCouncil.json
uk_bin_collection/uk_bin_collection/councils/BasingstokeCouncil.py

If a property in Basingstoke is subscribed to the Garden Waste Collection service, the bin collection date page additionally shows the dates for the Garden service. This change allows those to be collected (without breaking it for properties that aren't subscribed).

Add garden waste collection dates for Basingstoke Council

---

.github/workflows/release.yml

Closes #56 (if all goes well)
@robbrad This will need you to set up a PyPi account if you don't already have one and then I believe to set up another environment with the PYPI_API_KEY secret added containing the secret from your account.
The action will only run on tag creation at present so we'll be controlling when new releases happen manually.
It should replace `version = "0.1.0"` in `pyproject.toml` with the tag version that's being released automatically, not sure if this is the best practice as the repo's `pyproject.toml` will remain as 0.10 always unless we automate that changing/commit upping that as part of creating a new tag.
Let me know if there's any issues with the action/any of this.

Add release action to build and publish to PyPi

---

uk_bin_collection/uk_bin_collection/councils/CharnwoodBoroughCouncil.py

Fix for test failing with "ValueError: time data 'Today' does not match format '%a %d %b'" since the common format changes

Fix Charnwood Borough Council

---

pyproject.toml
uk_bin_collection/uk_bin_collection/collect_data.py
uk_bin_collection/uk_bin_collection/get_bin_data.py

Prevent JSON output being printed as well as being returned when calling the library

Move JSON printing to main function

---

uk_bin_collection/tests/council_schemas/AylesburyValeCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/AylesburyValeCouncil.json
uk_bin_collection/uk_bin_collection/councils/AylesburyValeCouncil.py

Adding support for Aylesbury Vale (part of Bucks Council) using their SOAP endpoint which returns XML, so tests may not pass if expecting JSON.
This endpoint is used by their mobile app and works only for domestic properties, not businesses.
Addresses request #312

Add support for Aylesbury Vale Council

---

uk_bin_collection/tests/council_schemas/GuildfordCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/GuildfordCouncil.json
uk_bin_collection/uk_bin_collection/councils/GuildfordCouncil.py

Adds support for Guildford Council using their Salesforce API which returns JSON.
Note that the endpoint will switch from 'collectionDate' to 'previousCollectionDate' at 7AM GMT on the bin day but I have included both dates in the output.
Addresses request #172

Added support for Guildford Council

---

uk_bin_collection/tests/council_schemas/LancasterCityCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/LancasterCityCouncil.json
uk_bin_collection/uk_bin_collection/councils/LancasterCityCouncil.py

Adds support for collecting waste collection dates from the Lancaster City Council website.
Sadly, most of the process to obtain the dates relies on a session in which the state is server-side...

Added support for Lancaster City Council

---

uk_bin_collection/tests/council_schemas/AylesburyValeCouncil.schema
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/AylesburyValeCouncil.json
uk_bin_collection/uk_bin_collection/councils/AylesburyValeCouncil.py

Added more collections in the future plus previous collections returned by the API.
+ More efficient code.

Added more output to Aylesbury Vale Council

---

custom_components/uk_bin_collection/sensor.py

Fixes #318 by telling the dateutil parser that we have the day first.
Changed the date comparison logic to remove the time portion i.e. `collection_date.date() >= current_date.date():`

Fixed date issues.

---

.github/workflows/release.yml
pyproject.toml

Update pyproject.toml manually to get the Bolton Council fix out for @rjosborne
Update release.yml to fix auto-updating the pyproject.toml version for PyPi and also now create a PR to update the repository to match.

Update pyproject.toml and release action

---

custom_components/uk_bin_collection/config_flow.py
custom_components/uk_bin_collection/sensor.py

This allows for multiple properties (such as pulling data for relatives) as well as when we're testing.
This also mitigates the potential issue of a second instance using the same entity names as it prefixes the location name to the entities.

Add support for multiple instances of the custom component

---

uk_bin_collection/tests/council_schemas/ReigateAndBansteadBoroughCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/ReigateAndBansteadBoroughCouncil.json
uk_bin_collection/uk_bin_collection/councils/ReigateAndBansteadBoroughCouncil.py

feat: Add support for Reigate and Banstead Borough Council

---

uk_bin_collection/tests/input.json

May close #346 
A quick fix to try and get this one working for @nmcrae85
This will result in the URL being called twice (once by the get data then again by selenium) so a better solution should be implemented when possible to avoid potential issues with Imperva captcha flagging the IP address.

fix: Fix for Wakefield City Council custom component support

---

uk_bin_collection/tests/council_schemas/RhonddaCynonTaffCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/RhonddaCynonTaffCouncil.json
uk_bin_collection/uk_bin_collection/councils/RhonddaCynonTaffCouncil.py
wiki/Councils.md

Hello, hello. It's me.
This closes #357 very nicely. Please let me know if I have broken anything... it has been a while hahaha.

feat: Add Rhondda Cynon Taff

---

custom_components/uk_bin_collection/config_flow.py

Closes #364
Remove the options flow/button from home assistant custom component due to it not working and to prevent confusion when there are issues with a council/configuration.
Users can simply remove and re-add the component to re set-up instead.

fix: Remove options flow from home assistant custom component

---

poetry.lock
pyproject.toml

Potential fix for Home Assistant conflicting dependencies error ref #365 & #347

fix: Update poetry.lock to allow any urllib3 version

---

.github/ISSUE_TEMPLATE/COUNCIL_ISSUE.yaml
.github/ISSUE_TEMPLATE/COUNCIL_REQUEST.yaml
.github/ISSUE_TEMPLATE/HOME_ASSISTANT_CUSTOM_COMPONENT_ISSUE.yaml

Fix auto-labeling new council requests
Add 2 new issue templates for existing council & HA custom component issues

docs: Update council request issue template

---

uk_bin_collection/tests/council_schemas/StratfordUponAvonCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/StratfordUponAvonCouncil.json
uk_bin_collection/uk_bin_collection/councils/StratfordUponAvonCouncil.py

Please let me know if I have fulfilled all the requirements, it seems to pass the initial tests. I do not have it installed on my HA setup yet, but intend to.

StratfordUponAvonCouncil Addition

---

uk_bin_collection/tests/council_schemas/BuryCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/BuryCouncil.json
uk_bin_collection/uk_bin_collection/councils/BuryCouncil.py
wiki/Councils.md

feat: Add support for Bury Council

---

uk_bin_collection/tests/input.json

My bad, committed wrong version of test input json with a missing comma 🤦

feat: fix missing comma in test input for eastsuffolkcouncil

---

uk_bin_collection/tests/council_schemas/CannockChaseDistrictCouncil.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/CannockChaseDistrictCouncil.json
uk_bin_collection/uk_bin_collection/councils/CannockChaseDistrictCouncil.py

feat: Add support for Cannock Chase District Council

---

uk_bin_collection/tests/council_schemas/ChelmsfordCityCouncil.schema
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/ChelmsfordCityCouncil.json
uk_bin_collection/uk_bin_collection/councils/ChelmsfordCityCouncil.py

fix: Fix Chelmsford City Council

---

uk_bin_collection/tests/council_schemas/ConwyCountyBorough.schema
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/tests/outputs/ConwyCountyBorough.json
uk_bin_collection/uk_bin_collection/councils/ConwyCountyBorough.py

feat: Add support for Conwy council

---

uk_bin_collection/tests/test_common_functions.py
uk_bin_collection/uk_bin_collection/common.py
uk_bin_collection/uk_bin_collection/councils/NorthTynesideCouncil.py

fix: #399 - DeprecationWarning: Python Package holidays

---

uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/step_defs/test_validate_council.py

fix: 419-fix-selenium-behave-tests

---

custom_components/uk_bin_collection/translations/en.json

Add missing line from translations to allow the custom component's web driver field to show a label

fix: Custom component web driver field label

---

uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/ShropshireCouncil.py

Closes https://github.com/robbrad/UKBinCollectionData/issues/477

feat: Add Shropshire Council

---

uk_bin_collection/tests/input.json

Recently merged Vale of White Horse Council in #524 shouldn't request URL in Home Assistant

fix: don't ask for URL for Vale of White Horse Council

---

.github/workflows/behave.yml
.github/workflows/codeql-analysis.yml
CONTRIBUTING.md
Makefile
uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/uk_bin_collection/councils/CheshireEastCouncil.py
uk_bin_collection/uk_bin_collection/councils/ConwyCountyBorough.py

Closes #534 
The pipeline now automatically detects councils that have changed and only runs intergrations tests against them
If no councils are changed then the whole set runs

Behave pipeline changes

---

uk_bin_collection/uk_bin_collection/councils/WakefieldCityCouncil.py

Remove the duplicate `driver.quit()` call, regardless of exception, finally is always called. 
Duplicate calls of `driver.quit()` cause error described in #556

fix: duplicate driver.quit() calls causes error

---

uk_bin_collection/uk_bin_collection/councils/BedfordshireCouncil.py
wiki/Councils.md

Now works on a variable amount of data, to account for the website changes. Example:
```bash
$ python collect_data.py BedfordshireCouncil https://www.centralbedfordshire.gov.uk/info/163/bins_and_waste_collections_-_check_bin_collection_day -p "SG19 2UP" -u "10000802040"
{
"bins": [
{
"type": "Food waste",
"collectionDate": "11/01/2024"
},
{
"type": "Garden waste",
"collectionDate": "11/01/2024"
},
{
"type": "Recycling",
"collectionDate": "11/01/2024"
},
{
"type": "Food waste",
"collectionDate": "18/01/2024"
},
{
"type": "Refuse (black bin)",
"collectionDate": "18/01/2024"
},
{
"type": "Food waste",
"collectionDate": "25/01/2024"
},
{
"type": "Garden waste",
"collectionDate": "25/01/2024"
},
{
"type": "Recycling",
"collectionDate": "25/01/2024"
},
{
"type": "Food waste",
"collectionDate": …
```

fix: update logic to account for council website change

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/ValeofWhiteHorseCouncil.py
wiki/Councils.md

The strings used previously were quite long and subject to change. This
isn't helpful as home assistant will build entity names based
on the bin_type value passed to it, so instead we'll scrape the info
and set appropriate static values for the bin type value.
Also ran the wiki generation script (I believe this step is failing in GitHub Actions currently)

Improvements for Vale of White Horse

---

uk_bin_collection/uk_bin_collection/councils/EastSuffolkCouncil.py

additional driver.quit() left in this council is causing errors -- maybe there's more councils with this too?

fix: East Suffolk Council - remove extra driver.quit() to prevent errors

---

uk_bin_collection/uk_bin_collection/councils/BarnetCouncil.py

The table of overrides for xmas has been removed, gracefully handle this - and if / when it gets recreated continue to use it

fix: barnet no overrides

---

uk_bin_collection/uk_bin_collection/councils/CharnwoodBoroughCouncil.py

moves year addition to before the parsing so it doesnt give the out of range error.

fix: fixed charnwood dates if in leap year

---

uk_bin_collection/uk_bin_collection/councils/MertonCouncil.py

Couple of changes here:
- fixes the dictionary data to look for `type` instead of `bin_type` (good eye @r-kc 😄)
- sorts the data in collection order rather than order scraped 
Closes #609.

fix: sort data and correct dictionary name (#609)

---

pyproject.toml
uk_bin_collection/uk_bin_collection/collect_data.py

This fixes the issue of inability to use the script installed via pip (#642).
Do let me know if there's a good way to add an automated test for this.

Fix incorrect script path in `pyproject.toml`

---

uk_bin_collection/uk_bin_collection/councils/LiverpoolCityCouncil.py

As seen in test runner output: https://robbrad.github.io/UKBinCollectionData/3.11/1743/index.html#categories/5b2af2f532711d70c78e691856a9d9af/a1887e7f3e3cd65c/

fix: add support for parsing "Tomorrow" as date text for `LiverpoolCityCouncil`

---

uk_bin_collection/uk_bin_collection/councils/BarnsleyMBCouncil.py

As seen in test runner output: https://robbrad.github.io/UKBinCollectionData/3.11/1743/index.html#categories/bcd21e910cdc04c35c478612db335974/c57295e0ec3a34c4/

fix: add support for parsing "Today" / "Tomorrow" as date text for `BarnsleyMBCouncil`

---

uk_bin_collection/uk_bin_collection/councils/HuntingdonDistrictCouncil.py

Closes #684.
Rewrote the parser so that the bin type is pulled from the site rather than a static text field. This also allowed for checking if a garden waste collection was available, which is now skipped if not, and was responsible for throwing the AttributeError.

Fix AttributeError on HuntingdonDistrictCouncil.py

---

uk_bin_collection/tests/input.json
uk_bin_collection/tests/test_common_functions.py

Now that `MiltonKeynesCityCouncil` test runner issue is resolved, it reveals the real test failure, that this source no longer works, as the page has changed to a PDF - see https://github.com/robbrad/UKBinCollectionData/issues/702

fix: test runners for `MiltonKeynesCityCouncil` and `NorthEastLincs`.

---

uk_bin_collection/uk_bin_collection/councils/DoverDistrictCouncil.py

fix: #709 Update DoverDistrictCouncil.py

---

uk_bin_collection/uk_bin_collection/councils/BarnsleyMBCouncil.py

fix: #713 BarnsleyMBCouncil.py

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/CheshireWestAndChesterCouncil.py

fix: #693 Cheshire West & Chester Council Sensor Bug

---

uk_bin_collection/uk_bin_collection/councils/BarnetCouncil.py

Fix accepting cookies before entering postcode

fix: Handle Barnet council cookies message

---

uk_bin_collection/tests/features/validate_council_outputs.feature
uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/BracknellForestCouncil.py

feat: Add support for Bracknell Forest Council

---

uk_bin_collection/uk_bin_collection/councils/CrawleyBoroughCouncil.py

I haven't opened an issue since I'd already found a fix, but the Crawley Borough Council website is slightly inconsistent with the formatting when a Garden Waste bin is registered at the property:
```
<div class="block-title">
<div class="title">
Rubbish and Small Electricals Collection
</div>
<i class="fa fa-trash" aria-hidden="true"></i>
</div>
```
vs
```
<div class="block-title">
GREENbin Garden Waste Collection 
<i class="fa fa-trash" aria-hidden="true"></i>
</div>
```
As such, the search for a type fails:
```
(uk-bin-collection-py3.11) matt@kessel:~/projects/UKBinCollectionData/uk_bin_collection/uk_bin_collection$ python collect_data.py CrawleyBoroughCouncil https://my.crawley.gov.uk/ -s -u <REDACTED>-n <REDACTED>
Traceback (most recent call last):
File …
```

fix: Crawley Borough Council inconsistent formatting

---

uk_bin_collection/uk_bin_collection/councils/GedlingBoroughCouncil.py

Following #763. I noticed you are having to do some replace calls on the original name generated from the iCal. There's also a bug whereby certain values that are changed collections become `Black Bin  (Changed )` after the replace calls.
All JSON endpoints now provide an `alternativeName` value for any collection, which provides a modified name value which removes the "Day" or "(Changed Collection)" values, which is cleaner for this use case. This is automatically generated at build, allowing you to simplify your codebase.
Here's the new values of name vs alternativeName:
| Name    | Alternative name |
| -------- | ------- |
| Black Bin Day (Changed Collection) | Black Bin |
| Green Bin Day | Green Bin |
| Green Bin + Glass Box Day | Green Bin + Glass Box |
| Garden Waste Collection | …

Gedling Borough Council: Use alternative name for cleaner values

---

uk_bin_collection/uk_bin_collection/councils/BirminghamCityCouncil.py

Incorrect path leads to import error:
```
Traceback (most recent call last):
File "/lsiopy/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 134, in <module>
run()
File "/lsiopy/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 130, in run
print(app.run())
^^^^^^^^^
File "/lsiopy/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 100, in run
council_module = import_council_module(self.parsed_args.module)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 19, in import_council_module
return importlib.import_module(module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

fix module name in BirminghamCityCouncil.py

---

uk_bin_collection/uk_bin_collection/councils/WakefieldCityCouncil.py

fix: #773 Wakefield

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/GloucesterCityCouncil.py

Fixes #565.
```
$ PYTHONPATH=. python3 uk_bin_collection/uk_bin_collection/collect_data.py GloucesterCityCouncil https://gloucester-self.achieveservice.com/en/service/Bins___Check_your_bin_day -p "GL2 5EX" -n 73 -u 10007315012
{
"bins": [
{
"type": "Household waste (black bin)",
"collectionDate": "13/09/2024"
},
{
"type": "Household recycling (green box, brown food bin and blue sack)",
"collectionDate": "13/09/2024"
}
]
}
```

Add Gloucester city council driver

---

uk_bin_collection/uk_bin_collection/councils/HighPeakCouncil.py

Fixes #824 
Seems to be safe to ignore the cookie dialog now.

fix: High Peak have changed their cookie dialog

---

uk_bin_collection/tests/input.json

fixes robbrad/UKBinCollectionData/issues/846
adds house number to input.json. HACS creation of integration using new input.json then prompts for house number which was missing previously. New entities are created and Home Assistant no longer crashes
Documentation in the wiki needs updating to reflect the requirement to specify a house number as part of the command line.

bug: Bracknell Forest configuration incorrect

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/BasildonCouncil.py

Adding Basildon Council (Essex)

feat: Adding Basildon Council

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/LincolnCouncil.py
uk_bin_collection/uk_bin_collection/councils/PerthAndKinrossCouncil.py
uk_bin_collection/uk_bin_collection/councils/TunbridgeWellsCouncil.py
wiki/Councils.md

fix: #572 
fix: #598 
fix: #748

feat: Council Pack 5

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/DudleyCouncil.py
uk_bin_collection/uk_bin_collection/councils/NorwichCityCouncil.py
uk_bin_collection/uk_bin_collection/councils/PlymouthCouncil.py
uk_bin_collection/uk_bin_collection/councils/SouthRibbleCouncil.py
wiki/Councils.md

fix: #749 
fix: #566 
fix: #671 
fix: #744

feat: Council Pack 6

---

uk_bin_collection/uk_bin_collection/councils/BarnsleyMBCouncil.py

Fixes #918 
Barnsley parser was correctly splitting bins that appeared on "upcoming collections" but not "next collection". This change refactors the code to re-use the splitting logic in both places.
Also, an enhancement is added to ensure that bins are not added twice.
Output before change (as of today):
```json
{
"bins": [
{
"type": "Brown, Green bin",
"collectionDate": "22/10/2024"
},
{
"type": "Grey bin",
"collectionDate": "29/10/2024"
},
{
"type": "Blue bin",
"collectionDate": "05/11/2024"
},
{
"type": "Green bin",
"collectionDate": "05/11/2024"
},
{
"type": "Grey bin",
"collectionDate": "12/11/2024"
}
]
}
```
Output after change:
```json
{
"bins": [
{
"type": "Brown bin",
"collectionDate": "22/10/2024"
},
{
"type": "Green bin",
"collectionDate": "22/10/2024"
},
{
"type": "Grey …
```

fix: #918 update Barnsley parser to fix combined bin

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/MidlothianCouncil.py

The Midlothian Council scraper is not functioning as intended due to frequently changing individual property URLs, which were previously thought to be static. The scraper has been updated to reflect this and now requires house number and postcode to be passed as parameters. This is a Breaking Change.

fix: Refactor Midlothian Council scraper to use house number and postcode

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/FifeCouncil.py
uk_bin_collection/uk_bin_collection/councils/FlintshireCountyCouncil.py
uk_bin_collection/uk_bin_collection/councils/SouthwarkCouncil.py
uk_bin_collection/uk_bin_collection/councils/StocktonOnTeesCouncil.py
uk_bin_collection/uk_bin_collection/councils/WestBerkshireCouncil.py
wiki/Councils.md

fix: #750 
fix: #933 
fix: #930

feat: Council Pack 9

---

.devcontainer/dev.Dockerfile
.devcontainer/devcontainer.json
.github/ISSUE_TEMPLATE/HOME_ASSISTANT_CUSTOM_COMPONENT_ISSUE.yaml
.github/workflows/behave.yml
.github/workflows/release.yml
.github/workflows/wiki.yml
.gitignore
.vscode/launch.json
CONTRIBUTING.md
Makefile
README.md
conftest.py
custom_components/uk_bin_collection/config_flow.py
custom_components/uk_bin_collection/sensor.py
custom_components/uk_bin_collection/strings.json
custom_components/uk_bin_collection/tests/test_config_flow.py
custom_components/uk_bin_collection/tests/test_sensor.py
custom_components/uk_bin_collection/translations/cy.json
custom_components/uk_bin_collection/translations/en.json
custom_components/uk_bin_collection/translations/ga.json
custom_components/uk_bin_collection/translations/gd.json
custom_components/uk_bin_collection/translations/pt.json
pyproject.toml
pytest.ini

**Potential breaking change:** We are moving to **Python 3.12** only to align to Home Assistant
I have also added unit testing to the Custom Component to add robustness to the sensor.py and config_flow.py

feat: Python 3.12 only and CustomComp. Unit testing

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/BrecklandCouncil.py
uk_bin_collection/uk_bin_collection/councils/CotswoldDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/StHelensBC.py
wiki/Councils.md

fix: #656 
fix: #658 
fix: #941 
fix: #753

feat: Council Pack 11

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/BlabyDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/BromsgroveDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/CarmarthenshireCountyCouncil.py
uk_bin_collection/uk_bin_collection/councils/EastAyrshireCouncil.py
uk_bin_collection/uk_bin_collection/councils/EastLindseyDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/SeftonCouncil.py
wiki/Councils.md

fix: #955 
fix: #892 
fix: #710 
fix: #957 
fix: #893 
fix: #770 
fix: #904

feat: Council Pack 12

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/ArgyllandButeCouncil.py
uk_bin_collection/uk_bin_collection/councils/AshfieldDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/BaberghDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/CheshireWestAndChesterCouncil.py
uk_bin_collection/uk_bin_collection/councils/DerbyCityCouncil.py
uk_bin_collection/uk_bin_collection/councils/GraveshamBoroughCouncil.py
uk_bin_collection/uk_bin_collection/councils/MidSuffolkDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/MiltonKeynesCityCouncil.py
wiki/Councils.md

fix: #987 
fix: #868 
fix: #919 
fix: #702 
fix: #993 
fix: #692 
fix: #991 
fix: #579

fix: Council Pack 15

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/BaberghDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/CumberlandAllerdaleCouncil.py
uk_bin_collection/uk_bin_collection/councils/EnvironmentFirst.py
uk_bin_collection/uk_bin_collection/councils/HartlepoolBoroughCouncil.py
uk_bin_collection/uk_bin_collection/councils/LondonBoroughHavering.py
uk_bin_collection/uk_bin_collection/councils/MidSuffolkDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/NewcastleUnderLymeCouncil.py
uk_bin_collection/uk_bin_collection/councils/NorthHertfordshireDistrictCouncil.py
wiki/Councils.md

fix: #1028 
fix: #1029 
fix: #1026 - This will require the use of a DAY to be added to the UPRN field
fix: #1025 
fix: #769 
fix: #778 
fix: #844

feat: Council Pack 18

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/CheltenhamBoroughCouncil.py
uk_bin_collection/uk_bin_collection/councils/CotswoldDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/EastAyrshireCouncil.py
uk_bin_collection/uk_bin_collection/councils/FolkstoneandHytheDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/HackneyCouncil.py
uk_bin_collection/uk_bin_collection/councils/KingsLynnandWestNorfolkBC.py
uk_bin_collection/uk_bin_collection/councils/LondonBoroughLewisham.py
uk_bin_collection/uk_bin_collection/councils/MorayCouncil.py
uk_bin_collection/uk_bin_collection/councils/RoyalBoroughofGreenwich.py
uk_bin_collection/uk_bin_collection/councils/SandwellBoroughCouncil.py
uk_bin_collection/uk_bin_collection/councils/ThurrockCouncil.py
uk_bin_collection/uk_bin_collection/councils/WestNorthamptonshireCouncil.py
uk_bin_collection/uk_bin_collection/councils/WyreForestDistrictCouncil.py
wiki/Councils.md

fix: #653 
fix: #668 
fix: #755 
fix: #766 
fix: #802 
fix: #1036 
fix: #891 
fix: #934 
fix: #1022 
fix: #858 
fix: #1045 
fix: #942 
fix: #836

feat: Council Pack 19

---

uk_bin_collection/uk_bin_collection/councils/LondonBoroughLewisham.py

fixes #1064
I've solved this by using a regex, which is hopefully more durable?
I've also update the webdriver to use "with", so that it closes out the driver when it's finished (I found that it wouldn't close the browser/tab when doing my testing, causing some issues).

fix: London Borough of Lewisham to have more reliable parsing of dates

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/BlabyDistrictCouncil.py
uk_bin_collection/uk_bin_collection/councils/BlackburnCouncil.py
uk_bin_collection/uk_bin_collection/councils/CarmarthenshireCountyCouncil.py
uk_bin_collection/uk_bin_collection/councils/GlasgowCityCouncil.py
uk_bin_collection/uk_bin_collection/councils/HighPeakCouncil.py
uk_bin_collection/uk_bin_collection/councils/HinckleyandBosworthBoroughCouncil.py
uk_bin_collection/uk_bin_collection/councils/MonmouthshireCountyCouncil.py
uk_bin_collection/uk_bin_collection/councils/WarwickDistrictCouncil.py
wiki/Councils.md

fix: #1055 - Carmarthenshire County Council - Will need to revisit this in 2025 when the new garden schedule is published
fix: #823 - Adding Hinckley and Bosworth Borough Council
fix: #832 - Adding Monmouthshire County Council
fix: #1058  - Fixing High Peak Council
fix: #1048 - Fixing Blackburn Council
fix: #1030  - Fixing Warwick District Council
fix: Blaby District Council

feat: Council Pack 20

---

uk_bin_collection/tests/test_common_functions.py
uk_bin_collection/uk_bin_collection/collect_data.py
uk_bin_collection/uk_bin_collection/common.py

A few more functions for common.py - these may be useful for calendars where we know the collection day, but have no way of scraping data and have to use our own functions to generate them.
A counterpart to is_holiday(), provides an easy way of finding out if a date is on a Saturday/Sunday.
I'm defining 'working day' as any day Monday to Friday that is not a holiday. This function is a wrapper for both is_holiday and is_weekend - if one is True for the given date, false is returned.
Could be useful when used with the above - returns the next working day according to the criteria above

Add three new functions to common.py

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/HartDistrictCouncil.py

Proposed feature to add support for Hart District Council (requested here: [Fleet, Hart Council #1038](https://github.com/robbrad/UKBinCollectionData/issues/1038))

Feature: Hart District Council

---

uk_bin_collection/uk_bin_collection/councils/BroxbourneCouncil.py

I've missed this in my previous PR. 
The council's dates are provided in `day/month` format, and the script was incrementing the year if the current month was January. This worked fine for December or November but caused issues when viewing dates in January. 
I've updated the script to increment the year for January dates only when parsed in a month other than January.

fix: correctly handle year increment for January dates (Broxbourne Council)

---

uk_bin_collection/uk_bin_collection/councils/MonmouthshireCountyCouncil.py

For Monmouthshire council, some collection date tags have new lines in them, therefore they must also be removed before parsing to check if the line starts with "Your next collection date is"
Just copied the text function from line 42, which already does this

Fix Monmouthshire collection new line error

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/BrentCouncil.py
uk_bin_collection/uk_bin_collection/councils/CornwallCouncil.py
uk_bin_collection/uk_bin_collection/councils/CumberlandCouncil.py
uk_bin_collection/uk_bin_collection/councils/DenbighshireCouncil.py
uk_bin_collection/uk_bin_collection/councils/DundeeCityCouncil.py
uk_bin_collection/uk_bin_collection/councils/GwyneddCouncil.py
uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py
uk_bin_collection/uk_bin_collection/councils/LondonBoroughSutton.py
uk_bin_collection/uk_bin_collection/councils/NorthumberlandCouncil.py
uk_bin_collection/uk_bin_collection/councils/OadbyAndWigstonBoroughCouncil.py
uk_bin_collection/uk_bin_collection/councils/WalthamForest.py
uk_bin_collection/uk_bin_collection/councils/WestDunbartonshireCouncil.py
wiki/Councils.md

Another bunch of council fixes and updates
fix: #1131 - London Borough Sutton
fix: #1129 - BREAKING CHANGE - Kirklees Council - This will require reconfiguration to use property UPRN instead of Postcode and Number
fix: #1126 - Waltham Forest
fix: #1110 - BREAKING CHANGE - Copeland Council has been replaced by Cumberland Council
fix: #1082 - Northumberland Council
fix: #1134 - Adding West Dunbartonshire Council
fix: #1109 - Adding Brent Council
fix: #1108 - Adding Dundee City Council
fix: #1106 - Adding Denbighshire Council
fix: #1125 - Adding Gwynedd Council
fix: #1137 - Fixing Cornwall Council
fix: #819 - Carlisle City Council is covered under Cumberland Council
fix: #929 - Adding Oadby And Wigston Borough Council

2025 Council Pack 1

---

uk_bin_collection/uk_bin_collection/councils/RushcliffeBoroughCouncil.py

Some controls had changed their IDs and the transition to the final panel wasn't being picked up anymore. This also fixes a warning about use of `\d` in a regex by declaring it as a raw string.

fix: Update Rushcliffe Borough Council input elements and flow 

---

README.md

This pull request improves the guide for hosting a Selenium instance on a Home Assistant Supervised setup. The changes include:
- **Clarified Instructions:** Reworded and reorganized steps to ensure they are concise, clear, and easy to follow, especially for users unfamiliar with Docker or Portainer.
- **Added Context:** Explained key actions and decisions, such as why the seleniarm/standalone-chromium:latest image is used.
- The original guide lacked structure and readability, which could lead to confusion or errors during setup.
- Clearer instructions help users complete the process efficiently, especially for those with limited technical expertise.
- Markdown formatting ensures the guide is compatible with various platforms, including GitHub, and aligns with documentation best …

docs: Added guidance on configuring Selenium within Home Assistant OS

---

uk_bin_collection/uk_bin_collection/councils/SouthOxfordshireCouncil.py

Fixes https://github.com/robbrad/UKBinCollectionData/issues/1160

fix: Update bin type to be the full string

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/LondonBoroughOfRichmondUponThames.py

I was able to run the individual test on local browser but struggled to run all the tests using the docker container.

feat:943 Adding support for Londong Borough of Richmond Upon Thames Council

---

uk_bin_collection/uk_bin_collection/councils/NewForestCouncil.py

Updated garden waste next collection date search as layout/element changed to a table with the day and date of next collection.
Have tested against multiple UPRNs and postcodes and appears to be bringing back the correct info.

fix: NewForestCouncil

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/HerefordshireCouncil.py

I'm sure there's probably room for improvement here. Still figuring out BS4 and Python so there might be a better way to grab the dates. Not sure if raising exceptions/errors is acceptable but figured it was nicer than crashing out in the for loop.

feat: Add Herefordshire Council (closes: #1023)

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/CheltenhamBoroughCouncil.py

Change for Cheltenham Borough Council to be a dynamic lookup per location as opposed to a static offset. This is due to the awkward day/week relationship for each type of bin at each address.
This still has issues for some addresses that have multiple addresses for a given X/Y coordinate, which also appears to translate to multiple bin collection patterns per USRN.
The main detail that changes for these situations is a description of what addresses each one covers. This sometimes refers to buildings, streets, house numbers, or other.

Fix: #1061 for CheltenhamBoroughCouncil

---

uk_bin_collection/uk_bin_collection/councils/HackneyCouncil.py

Parse scheduleCodeWorkflowIDs instead of scheduleCodeWorkflowID for Hackney Council
Use the first element of scheduleCodeWorkflowIDs (plural) in place of scheduleCodeWorkflowID
fix: #1267

fix: parse scheduleCodeWorkflowIDs instead of scheduleCodeWorkflowID

---

uk_bin_collection/uk_bin_collection/councils/SouthOxfordshireCouncil.py

Fixes #1317
It looks like in a previous change to handle the bins being on a different day the `bin_type` variable was missed out and now causing the extension to crash on load due to unset variable.

fix: Set the bin_type when different day

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/SandwellBoroughCouncil.py

Fixes: https://github.com/robbrad/UKBinCollectionData/issues/1334
The id `58a1a71694992` used in the calls returns only the householde waste:
Before we were giving these values to all the bin types, but this is not true for the garden waste which is collected on different days.
The id `56b1cdaf6bb43` is used to retrieve the data for the garden waste:
> Note:
> Some UPRNs return an empty list for garden waste collection dates.
> I have tried to check Sandwell's website but even in their calls it is
> coming back empty (even if the data is in the UI).
As well I've introduced Batteries as a bin type for Sandwell Borough Council.
This is a sample of what now is returned by the `parse_data` now:
```
{
'bins': [
{'type': 'Recycling (Blue)', 'collectionDate': '18/04/2025'}, 
{'type': 'Household …
```

fix: Sandwell garden waste collection date is wrong

---

uk_bin_collection/uk_bin_collection/councils/HarrogateBoroughCouncil.py

Fix for issue with Harrogate Borough Council html scraping.
I've tested the change using the python script, and also ran the tests in the dev container to prove the change fixes the issue.

Fix: #1359 - Harrogate Borough Council scraping issue

---

uk_bin_collection/uk_bin_collection/councils/HarrogateBoroughCouncil.py

The first table has now been re-added, so I have changed the code to look for the last table irrespective of how many tables there are, so it will always find the right one.

Fix: #1359 - HTML Parsing error with Harrogate Borough Council

---

uk_bin_collection/tests/input.json

As mentioned [here](https://github.com/robbrad/UKBinCollectionData/discussions/1364). Taken from [here](https://pages.mysociety.org/uk_local_authority_names_and_codes/downloads/uk_la_past_current_json/latest). 
Also removed Brighton's UPRN since it doesn't use it.
[uk_la_past_current.json](https://github.com/user-attachments/files/19865380/uk_la_past_current.json)

fix: used canonical 'nice name'

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/SloughBoroughCouncil.py

As per this request https://github.com/robbrad/UKBinCollectionData/issues/1105
Slough is a tricky website because it's non-standard. It doesn't take a UPRN, postcode or house number.
I didn't want to turn this into a special case, so I found the street name from a Google API [postcode lookup](https://maps.googleapis.com/maps/api/geocode/json?address=SL2+2EW&key=AIzaSyBDLULT7EIlNtHerswPtfmL15Tt3Oc0bV8). The API can do 40,000 lookups for free each month so I don't see us exceeding that, but perhaps this isn't a desired solution.

feat: Added Slough Council

---

uk_bin_collection/uk_bin_collection/councils/CroydonCouncil.py

As per this issue https://github.com/robbrad/UKBinCollectionData/issues/1247
A rewrite in Selenium.

fix: Croydon selenium version

---

README.md
bin_to_ics.py

This PR adds a new feature that allows users to convert bin collection data into standard ICS calendar files. This enhancement makes the project more versatile by enabling users to integrate bin collection data with any calendar application that supports the ICS format, whether they use Home Assistant or not.
•  Standalone ICS Generator: New bin_to_ics.py script that converts JSON bin collection data to ICS format
•  Flexible Calendar Options:
•  All-day or timed events
•  Customizable calendar name
•  Multiple reminder/alarm options (e.g., "1d, 2h, 30m" before collection)
•  Groups multiple bin collections on the same day into single events
•  Integration Options:
•  Direct piping from bin collection data retriever
•  File-based input/output
•  Standard input/output support
1. Home …

Add ICS calendar generation feature

---

uk_bin_collection/uk_bin_collection/councils/NorthLincolnshireCouncil.py

RE: issue #1455 - update to use the common ordinal_remover.

fix #1455: remove ordinal indicators from bin collection date parsing

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/CroydonCouncil.py

This should fix the Croydon issues I was having. 
While debugging I noticed that bin_sections were coming back empty. After updating the wait-for-content function (as shown in this PR), the tests started passing consistently.
Also added the missing web_driver entry in input.json.

Simplify and fix wait for content, fixes Croydon council

---

uk_bin_collection/tests/input.json
uk_bin_collection/uk_bin_collection/councils/OxfordCityCouncil.py
wiki/Councils.md

Fixed Oxford City Council parsing Changes in output from the website, now correctly gets the bin types, tested using sample Postcode and UPRN from the Wiki and also the Postcode and UPRN listed in the bug, all works succesfully
this should resolve [this bug](https://github.com/robbrad/UKBinCollectionData/issues/1393)

fix(OxfordCityCouncil): Fixed Oxford City Council parsing Changes

---

uk_bin_collection/uk_bin_collection/councils/AdurAndWorthingCouncils.py

To fix this.
https://github.com/robbrad/UKBinCollectionData/issues/1454
If the collection date was today, then it would assume it was in the past and assume the collection date was next year.

AdurAndWorthingCouncils year fix

---

uk_bin_collection/uk_bin_collection/councils/BedfordshireCouncil.py

**Issue**
Bedfordshire Council website has been returning 403 responses which is resulting in the error `Unexpected error: 'NoneType' object has no attribute 'find_all'`
**Cause**
Bedfordshire Council is fronted by AWS. From simple tests it appears they are blocking the python-requests user agent as altering the user agent to something else allowed the request through. The issue was initially repro'd with a raw HTTP request and passing the python-requests user agent.
**Fix**
Pass a custom user agent value in the header when making the request to the Bedfordshire Council website.

Fix Bedfordshire Council (AWS) blocking python-requests user agent

---

uk_bin_collection/uk_bin_collection/councils/NewcastleUnderLymeCouncil.py

Add request headers to fix the following issue:
Newcastle-under-Lyme Council - 403 error #1501

Fix Newcastle-under-Lyme Council - Add request headers to resolve 403 Forbidden

---

uk_bin_collection/uk_bin_collection/councils/RoyalBoroughofGreenwich.py

Fixes #1496 by ensuring that the requests are not rejected due to lack of headers.

fix: Add headers to requests for Royal Borough of Greenwich

---

custom_components/uk_bin_collection/__init__.py
custom_components/uk_bin_collection/const.py

Fixed the handling of the headless argument in the build_ukbcd_args function to correctly pass boolean values as command-line flags.

Fix headless argument handling HACS Integration

---

uk_bin_collection/uk_bin_collection/councils/RochfordCouncil.py

Before:
```
% python3 -m uk_bin_collection.uk_bin_collection.collect_data RochfordCouncil https://www.rochford.gov.uk/online-bin-collections-calendar
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/Shared/GitHub/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 135, in <module>
run()
~~~^^
File "/Users/Shared/GitHub/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 131, in run
print(app.run())
~~~~~~~^^
File "/Users/Shared/GitHub/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 102, in run
return self.client_code(
~~~~~~~~~~~~~~~~^
council_module.CouncilClass(),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...<9 …
```

fix: RochfordCouncil date parsing
