- requirements.txt
- scripts/councils/CardiffCouncil.py
- scripts/councils/TorridgeDistrictCouncil.py
Added **kwargs support for Cardiff and Torridge.
Also added a requirements.txt file for people not using pipenv and pipfile (me included lol)
> More **kwargs support

- .gitignore
- scripts/councils/CrawleyBoroughCouncil.py
This should close #25.
Added some documentation [here](https://github.com/robbrad/UKBinCollectionData/wiki/Councils#crawley-borough-council).
Also changed the .gitignore to not ignore markdown files.
> Add support for Crawley Borough Council

- .github/workflows/behave.yml
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/SouthTynesideCouncil.json
- uk_bin_collection/uk_bin_collection/councils/SouthTynesideCouncil.py
This closes #4.
Special thanks to @ZackaryH8 for the Postman API making it a thousand times easier!
@robbrad I've added the items mentioned in #79 - could you check that it's all good please? 😀
> Add support for South Tyneside Council

- uk_bin_collection/tests/council_schemas/YorkCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/YorkCouncil.json
- uk_bin_collection/tests/test_collect_data.py
- uk_bin_collection/tests/test_common_functions.py
- uk_bin_collection/tests/test_uk_bin_collection.py
- uk_bin_collection/uk_bin_collection/councils/YorkCouncil.py
> Added support for York Council

- uk_bin_collection/tests/council_schemas/WindsorAndMaidenheadCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/WindsorAndMaidenheadCouncil.json
- uk_bin_collection/uk_bin_collection/councils/EastRidingCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WindsorAndMaidenheadCouncil.py
- uk_bin_collection/uk_bin_collection/councils/YorkCouncil.py
Closes #99.
Updated the wiki with the correct code to run too. Will probably need testing, but it's 2:17am and I want sleep lol.
> Add Windsor and Maidenhead Council

- uk_bin_collection/tests/council_schemas/ManchesterCityCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/ManchesterCityCouncil.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/CastlepointDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ManchesterCityCouncil.py
Closes #105.
Updated the wiki here: https://github.com/robbrad/UKBinCollectionData/wiki/Councils#manchester-city-council
> Add support for Manchester City Council

- uk_bin_collection/tests/council_schemas/BoltonCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/BoltonCouncil.json
- uk_bin_collection/uk_bin_collection/councils/BoltonCouncil.py
This will close #116.
Pretty simple parser. It will only currently show future dates - I'm guessing the source JSON is generated every one or two weeks for when the following collection is. I'm predicting this may need to be revisited in the future to either:
-  include sorting by date
-  scrape and build a proper scheduler
> Add support for Bolton Council

- uk_bin_collection/tests/council_schemas/DoncasterCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/DoncasterCouncil.json
- uk_bin_collection/uk_bin_collection/councils/DoncasterCouncil.py
Closes #118.
This one was fun - spent a lot of time finding Doncaster's own property ID, then realized you can grab results from the calendar directly with a UPRN 🤣. Anyways, another one in the bag!
> Add Doncaster Council

- uk_bin_collection/tests/council_schemas/FenlandDistrictCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/FenlandDistrictCouncil.json
- uk_bin_collection/uk_bin_collection/councils/FenlandDistrictCouncil.py
@Rustymage this is for you 😄 
Closes #16
> Add support for Fenland District Council

- uk_bin_collection/tests/council_schemas/BexleyCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/BexleyCouncil.json
- uk_bin_collection/uk_bin_collection/councils/BexleyCouncil.py
@vaderag was correct, the web form was excessively complex.
Luckily, the mobile app is incredibly easy to parse. Users will need to sign up to it with an email to use this parser, but at least it seems reliable.
Closes #123.
> Add Bexley Council

- uk_bin_collection/tests/council_schemas/SouthAyrshireCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/SouthAyrshireCouncil.json
- uk_bin_collection/uk_bin_collection/councils/SouthAyrshireCouncil.py
> Add South Ayrshire Council

- uk_bin_collection/tests/council_schemas/NewarkAndSherwoodDC.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/NewarkAndSherwoodDC.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/NewarkAndSherwoodDC.py
- Added parser and project files for Newark and Sherwood District Council
- Added a new common function for removing ordinal indicators (made use in this parser)
Closes #126.
> Add Newark and Sherwood District Council

- uk_bin_collection/tests/council_schemas/BCPCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/BCPCouncil.json
- uk_bin_collection/uk_bin_collection/councils/BCPCouncil.py
BCP = Bournemouth, Christchurch and Poole Council, but that takes a while to type out so here we are ¯\_(ツ)_/¯
Closes #6.
> Add BCP Council

- uk_bin_collection/tests/council_schemas/SouthOxfordshireCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/SouthOxfordshireCouncil.json
- uk_bin_collection/uk_bin_collection/councils/SouthOxfordshireCouncil.py
Seeing in my 28th birthday with this PR!
Closes #129 - should keep working but for some reason, I feel like it might break lol. We can cross that bridge should we get to it though.
> Add South Oxfordshire Council

- uk_bin_collection/uk_bin_collection/collect_data.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
+ the commit history that i then reverted because I tried to fix something that wasn't broken
> Remove console urllib3 error

- uk_bin_collection/tests/council_schemas/DurhamCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/DurhamCouncil.py
Hello there! Thanks for making this project - it was something I was thinking about making earlier in the year but never got round to looking up!
Love the integration tests, have done my best to add a new one in - I didn't notice any design document around how the UPRN should be taken, so I followed a pattern I saw in a couple other councils.
Hope this is ok!
> Add DurhamCouncil

- uk_bin_collection/uk_bin_collection/councils/WakefieldCityCouncil.py
Pretty sure the parser was broken anyways, but spoofing a web request to combat a firewall shouldn't harm either. This also should resolve #152.
> Updated Wakefield parser to use requests

- uk_bin_collection/tests/council_schemas/ValeofGlamorganCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/ValeofGlamorganCouncil.json
> Add Vale of Glamorgan Council project files

- uk_bin_collection/tests/council_schemas/NorthTynesideCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/NorthTynesideCouncil.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/NorthTynesideCouncil.py
This will fully close #150 now.
> Add support for North Tyneside Council

- uk_bin_collection/uk_bin_collection/common.py
Removed regex in common.py's check_postcode() function and replaced with API call to postcodes.io for better validation
> Add postcode API

- uk_bin_collection/tests/council_schemas/GlasgowCityCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/GlasgowCityCouncil.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/GlasgowCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/NorthTynesideCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ValeofGlamorganCouncil.py
Closes #148.
Wrote a function to calculate every X number of days, then realised I could parse a calendar page instead 🙃
> Add Glasgow City Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
Add missing integration tests ref issue #79
> Add EastRidingCouncil integration tests

- uk_bin_collection/tests/features/validate_council_outputs.feature
Add missing integration tests ref issue #79
> Add TamesideMBCouncil integration tests

- uk_bin_collection/uk_bin_collection/councils/NorthSomersetCouncil.py
> Disable Unverified HTTPS warnings for NorthSomersetCouncil

- uk_bin_collection/tests/council_schemas/CroydonCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/CroydonCouncil.json
- uk_bin_collection/uk_bin_collection/councils/CroydonCouncil.py
Closes #147.
Experienced some issues with blank responses if you make one of the requests too often, an error message of "Failed to get bin data. Too many requests. Please wait a few minutes before trying again." will be returned when this happens.
> Add support for Croydon Council

- uk_bin_collection/tests/council_schemas/MaldonDistrictCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/MaldonDistrictCouncil.json
- uk_bin_collection/uk_bin_collection/councils/MaldonDistrictCouncil.py
> Add support for Maldon District Council

- pyproject.toml
- uk_bin_collection/tests/council_schemas/Chilterns.schema
- uk_bin_collection/tests/features/steps/validate_council.py
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/Chilterns.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
Adds support for Chilterns Council, as requested by #154 (and potentially #38).
> Add support for Chilterns Council

- uk_bin_collection/tests/council_schemas/HighPeakCouncil.schema
- uk_bin_collection/tests/council_schemas/HuntingdonDistrictCouncil.schema
- uk_bin_collection/tests/council_schemas/StockportBoroughCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/HighPeakCouncil.json
- uk_bin_collection/uk_bin_collection/councils/HighPeakCouncil.py
Largely based on Chilterns as they appear to use similar systems.
Aslo fixed a few feature tests while I was trying to work out how it worked.
Should address #130
> Add support for High Peak Council

- uk_bin_collection/tests/council_schemas/NorthLincolnshireCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/NorthLincolnshireCouncil.json
- uk_bin_collection/uk_bin_collection/councils/NorthLincolnshireCouncil.py
> Add support for North Lincolnshire Council

- uk_bin_collection/tests/council_schemas/SomersetCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/SomersetCouncil.json
- uk_bin_collection/uk_bin_collection/SomersetCouncil.py
H/T to @canalla450 for the code and @OliverCullimore for finding it worked for more than one council and naming suggestion.
I had very little idea what this code did, but I changed it to use our dictionary format and kwargs 😂
- Sedgemoor (closes #171)
- Mendip District Council
- Somerset West and Taunton Council
- South Somerset District Council
> Add support for Somerset Councils

- uk_bin_collection/tests/council_schemas/RochdaleCouncil.schema
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/RochdaleCouncil.json
- uk_bin_collection/uk_bin_collection/councils/RochdaleCouncil.py
Probably needs testing added before merging. Any changes needed, just let me know.
> Add support for Rochdale Borough Council

- uk_bin_collection/tests/council_schemas/LondonBoroughHounslow.schema
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/LondonBoroughHounslow.json
- uk_bin_collection/uk_bin_collection/councils/LondonBoroughHounslow.py
ChatGPT is awesome 💯 
Closes #144
> Added LondonBoroughHounslow

- uk_bin_collection/tests/test_common_functions.py
- uk_bin_collection/uk_bin_collection/common.py
> #203 100% coverage on unit tests

- uk_bin_collection/tests/council_schemas/ErewashBoroughCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/ErewashBoroughCouncil.json
- uk_bin_collection/uk_bin_collection/councils/ErewashBoroughCouncil.py
Closes #207 
Wiki entry:
---
```commandline
python collect_data.py ErewashBoroughCouncil https://map.erewash.gov.uk/isharelive.web/myerewash.aspx -u XXXXXXXX
```
Additional parameters:
- `-u` - UPRN
> Add support for Erewash Borough Council

- .github/workflows/behave.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/wiki.yml
- .gitignore
- wiki/Councils.md
- wiki/Home.md
- wiki/Setup.md
Implementation of thought on #100 and kinda relates to #55 also.
Workflow is UNTESTED but follows the documentation so should, in theory, work as intended but happy to help fix it if not.
Includes updates to the other workflows to prevent them from running if only changes to the wiki Markdown pages are made in a push/pull request.
> Add wiki to repository with GitHub action to push to wiki

- uk_bin_collection/tests/council_schemas/LondonBoroughHounslow.schema
- uk_bin_collection/tests/input.json
> Fix London Borough Hounslow

- .github/workflows/behave.yml
- .github/workflows/codeql-analysis.yml
> 218 gh pages deploy issue

- .github/workflows/behave.yml
- .github/workflows/codeql-analysis.yml
Fixes related to #100 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
> #100 Workflow fixes

- uk_bin_collection/tests/council_schemas/MalvernHillsDC.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/MalvernHillsDC.json
- uk_bin_collection/tests/outputs/MalvernHillsDC.py
- uk_bin_collection/uk_bin_collection/councils/MalvernHillsDC.py
- wiki/Councils.md
Add support for MHDC. Hopefully fits in with the amazing work you guys have done here.
> Add Malvern Hills District Council

- .github/workflows/wiki.yml
- CONTRIBUTING.md
- Makefile
- uk_bin_collection/tests/input.json
- wiki/generate_wiki.py
> Generate Councils.md from input.json & fix some integration tests

- .github/workflows/wiki.yml
- wiki/Councils.md
Manually ran and committed the generated the wiki while the wiki workflow permissions are being fixed
Fix the wiki workflow not running on input.json being changed
Ref #100
> Update Councils.md from input.json

- uk_bin_collection/uk_bin_collection/collect_data.py
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/BlackburnCouncil.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
- wiki/generate_wiki.py
Ref #241 
Add development mode to collect_data.py to create/update outputs .json file for the council on each run
Also fix need for "true" after -s or --skip_get_url parameter for collect_data.py
And finally fix Unverified HTTPS warning for Blackburn Council ref #159
> 241 development mode

- CONTRIBUTING.md
> Add development mode to CONTRIBUTING.md

- uk_bin_collection/tests/council_schemas/MiltonKeynesCityCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/MiltonKeynesCityCouncil.json
- uk_bin_collection/uk_bin_collection/councils/MiltonKeynesCityCouncil.py
- wiki/Councils.md
Pretty sure I got everything new in the project files, though just might be worth checking 😇.
Closes #248 - just pass the estate in double quotes using UPRN
> Add support for Milton Keynes City Council

- uk_bin_collection/tests/council_schemas/MertonCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/MertonCouncil.json
- uk_bin_collection/uk_bin_collection/councils/MertonCouncil.py
This PR adds support for the Merton Council (in London)
First time doing python, so please let me know if I can improve anything...
> Add Merton Council

- uk_bin_collection/tests/council_schemas/WelhatCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/WelhatCouncil.json
- uk_bin_collection/uk_bin_collection/councils/WelhatCouncil.py
> Add support for Welhat Council

- CONTRIBUTING.md
- uk_bin_collection/tests/council_schemas/ChelmsfordCityCouncil.schema
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/ChelmsfordCityCouncil.json
- uk_bin_collection/uk_bin_collection/councils/ChelmsfordCityCouncil.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
Fix feature tests running after my `from common import write_output_json` in #242 broke them 🙃 
Update CONTRIBUTING with the new test commands
Fix Merton Council's input.json whitespace typo
Update Chelmsford City Council to fix it's feature test which also closes #156
> Feature test & other fixes

- uk_bin_collection/tests/council_schemas/EastleighBoroughCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/EastleighBoroughCouncil.json
- uk_bin_collection/uk_bin_collection/councils/EastleighBoroughCouncil.py
Adds support for Eastleigh Borough Council (Hampshire) to address/close #247
> Add Eastleigh BC support

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BromleyBoroughCouncil.py
Just a tidy up for the Bromley crawler so it reacts better to different bins (and so it passes the tests)
> Improve Bromley crawler (so it passes the tests)

- CONTRIBUTING.md
- uk_bin_collection/tests/council_schemas/SouthCambridgeshireCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/SouthCambridgeshireCouncil.json
- uk_bin_collection/uk_bin_collection/councils/SouthCambridgeshireCouncil.py
First attempt at reworking a previously crafted py script  to this format.
Think I've submitted the various files requested and it seemed to pass the Behave test.
Have to admit I found the [input.json](https://github.com/robbrad/UKBinCollectionData/blob/master/CONTRIBUTING.md#input-json-file) instructions a bit confusing, so that file may need tweaking.
It would be useful to also include an example where the parameters required are not part of the url, and when/if the `-s`  flag could/should be used?
Also corrected a broken link for `councilclasstemplate.py`in CONTRIBUTING.md.
> Add support for SouthCambs

- uk_bin_collection/tests/council_schemas/NorthumberlandCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/NorthumberlandCouncil.json
- uk_bin_collection/uk_bin_collection/councils/NorthumberlandCouncil.py
Uses selenium to get the page and then parses the colours from the calander and matches to the bin type.
> Add support for Northumberland Council

- uk_bin_collection/tests/council_schemas/WiltshireCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/WiltshireCouncil.json
- uk_bin_collection/uk_bin_collection/councils/WiltshireCouncil.py
- wiki/Councils.md
Closes #276. Nothing too fancy here 👀.
> Add support for Wiltshire Council

- uk_bin_collection/tests/council_schemas/RushmoorCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/RushmoorCouncil.json
- uk_bin_collection/uk_bin_collection/councils/RushmoorCouncil.py
> Add support for Rushmoor Council

- uk_bin_collection/tests/council_schemas/BasingstokeCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/BasingstokeCouncil.json
- uk_bin_collection/uk_bin_collection/councils/BasingstokeCouncil.py
- wiki/Councils.md
I believe I've done all this right, and it certainly seems to work.
> Add basingstoke scraper

- uk_bin_collection/tests/council_schemas/PrestonCityCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/PrestonCityCouncil.json
- uk_bin_collection/uk_bin_collection/councils/PrestonCityCouncil.py
Hey, cool project! 
I added a scraper for Preston City Council - seems to work well and has allowed me to get notifications in Home Assistant the night before the bins are due to be collected :slightly_smiling_face: 
You'll notice the scraper code works by just tacking the house number / name and the postcode together in the search box and selecting the first one from the dropdown which may in rare cases cause an issue if there are different collection dates for the same postcode but that's a real edge case
> Add Preston City Council

- uk_bin_collection/tests/council_schemas/BroxtoweBoroughCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/BroxtoweBoroughCouncil.json
- uk_bin_collection/uk_bin_collection/councils/BroxtoweBoroughCouncil.py
> Add support for Broxtowe Borough Council

- uk_bin_collection/tests/council_schemas/RushcliffeBoroughCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/RushcliffeBoroughCouncil.json
- uk_bin_collection/uk_bin_collection/councils/RushcliffeBoroughCouncil.py
> Add support for Rushcliffe Borough Council

- uk_bin_collection/tests/council_schemas/DerbyshireDalesDistrictCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/DerbyshireDalesDistrictCouncil.json
- uk_bin_collection/uk_bin_collection/councils/DerbyshireDalesDistrictCouncil.py
> Add support for Derbyshire Dales District Council

- uk_bin_collection/tests/council_schemas/CrawleyBoroughCouncil.schema
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/CrawleyBoroughCouncil.json
- uk_bin_collection/tests/step_defs/test_validate_council.py
- uk_bin_collection/tests/test_common_functions.py
- uk_bin_collection/uk_bin_collection/collect_data.py
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/CrawleyBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
- wiki/generate_wiki.py
Closes #198 
Closes #197 
Another **BREAKING CHANGE** as this removes the OS API use and adds a USRN parameter as `-us` which breaks the one-character normal format.
Possibly could use `-n` and note to pass the USRN through that field like we've done for other things instead if this is an issue.
Adds feature test files to fix the failing test also.
> Updates to Crawley Borough Council

- .github/workflows/behave.yml
- .github/workflows/release.yml
- .github/workflows/wiki.yml
- pyproject.toml
https://github.com/robbrad/UKBinCollectionData/issues/304
Update Python versions
> 304 python versions

- pyproject.toml
- uk_bin_collection/tests/step_defs/test_validate_council.py
- uk_bin_collection/uk_bin_collection/collect_data.py
https://github.com/robbrad/UKBinCollectionData/issues/306
> #306 collect data class

- README.md
- hacs.json
> Add support for installing via HACS custom repositories

- uk_bin_collection/uk_bin_collection/councils/BoltonCouncil.py
> Fix Bolton Council

- uk_bin_collection/uk_bin_collection/councils/WiganBoroughCouncil.py
Thanks to @rjosborne it's been spotted this one's output format wasn't fully updated to the new format
> Fix Wigan Borough Council output format

- .github/workflows/lint.yml
- .github/workflows/release.yml
- pyproject.toml
May close #333 if there aren't any issues with the action implementation
> Automate creating releases

- uk_bin_collection/tests/council_schemas/WakefieldCityCouncil.schema
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/WakefieldCityCouncil.json
- uk_bin_collection/uk_bin_collection/councils/WakefieldCityCouncil.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
Closes #339
It seems using Selenium we're able to get around the Imperva capture
> Fix Wakefield City Council

- .github/workflows/lint.yml
- .github/workflows/release.yml
Fixes python-semantic-release/python-semantic-release action to point to a version number which actually exists
> Fix release action

- uk_bin_collection/tests/council_schemas/BathAndNorthEastSomersetCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/BathAndNorthEastSomersetCouncil.json
- uk_bin_collection/uk_bin_collection/councils/BathAndNorthEastSomersetCouncil.py
> Add support for Bath and North East Somerset Council

- pyproject.toml
@robbrad looking good so far but errored on a missing comma with my last update
> ci: Fix pyproject.toml

- uk_bin_collection/tests/council_schemas/NeathPortTalbotCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/NeathPortTalbotCouncil.json
- uk_bin_collection/uk_bin_collection/councils/NeathPortTalbotCouncil.py
> feat: Add support for Neath Port Talbot Council

- uk_bin_collection/tests/council_schemas/EastLindseyDistrictCouncil.schema
- uk_bin_collection/tests/council_schemas/GatesheadCouncil.schema
- uk_bin_collection/tests/council_schemas/StaffordshireMoorlandsDistrictCouncil.schema
- uk_bin_collection/tests/council_schemas/WestLothianCouncil.schema
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/outputs/EastLindseyDistrictCouncil.json
- uk_bin_collection/tests/outputs/GatesheadCouncil.json
- uk_bin_collection/tests/outputs/StaffordshireMoorlandsDistrictCouncil.json
- uk_bin_collection/tests/outputs/WestLothianCouncil.json
- uk_bin_collection/uk_bin_collection/councils/EastLindseyDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/GatesheadCouncil.py
- uk_bin_collection/uk_bin_collection/councils/StaffordshireMoorlandsDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WestLothianCouncil.py
Closes #164
Closes #316
Closes #362
Closes #363
> Add support for multiple councils using similar systems

- uk_bin_collection/uk_bin_collection/councils/EastSuffolkCouncil.py
Just some fixes (driver quit too early etc)
Despite these fixes it still doesn't actually work in hass, other selenium ones do like North Norfolk District, so I don't know whats wrong with this one... Provides correctly formatted output as far as I can tell.
eg:
```json
{
"bins": [
{
"type": "General Waste",
"collectionDate": "09/11/2023"
},
{
"type": "Recycling",
"collectionDate": "16/11/2023"
}
]
}
```
> Fixes for EastSuffolkCouncil

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BoltonCouncil.py
Update Bolton scraper after council website change.
> Fix scraper for Bolton

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/EnvironmentFirst.py
Closes #433,
I originally intended on developing periods and renamed a function parameter for it, then decided not to lol. But the change made more sense so I left it in.
> feat: Add support for EnvironmentFirst collections

- uk_bin_collection/uk_bin_collection/councils/CharnwoodBoroughCouncil.py
> fix: Charnwood BC issues

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/StokeOnTrentCityCouncil.py
> feat: Add support for Stoke-on-Trent City Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/RugbyBoroughCouncil.py
> Add support for Rugby Borough Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/DorsetCouncil.py
> Add support for Dorset Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BarnsleyMBCouncil.py
> Add support for Barnsley Metropolitan Borough Council 

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/SevenoaksDistrictCouncil.py
> feat: Add Sevenoaks District Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NorthWestLeicestershire.py
> 174 north west leicestershire

- uk_bin_collection/uk_bin_collection/collect_data.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
Another go at a fix for #464 hopefully this time without breaking all the tests
> fix: move logging config to collect_data script

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NorthEastDerbyshireDistrictCouncil.py
> feat: adding NorthEastDerbyshireDistrictCouncil

- custom_components/uk_bin_collection/sensor.py
Fix for issue 394. No longer store data in a list and access via index, use bin_type keyed dictionary instead to prevent data being applied to the incorrect sensor.
> fix: Issue 394 - change coordinator data from numerical indexed list to dict

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ReadingBoroughCouncil.py
> feat: Adding support for Reading Borough Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ForestOfDeanDistrictCouncil.py
> feat: adding #204 Forest_of_Dean_District

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BlackburnCouncil.py
Moving Blackburn to Selenium closes #488
> fix: 488_blackburnfixes

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ForestOfDeanDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HaltonBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LeedsCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/NorthWestLeicestershire.py
- uk_bin_collection/uk_bin_collection/councils/OldhamCouncil.py
- uk_bin_collection/uk_bin_collection/councils/PortsmouthCityCouncil.py
Closes #244 #174 #244 #204 #250 #264 #141
> Council mega pack 1

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/RushmoorCouncil.py
Closes #266 - rewrote the parser to parse the XML doc into JSON, then load the data. Easy peasy.
> fix: Update Rushmoor Borough Council

- uk_bin_collection/uk_bin_collection/councils/LeedsCityCouncil.py
> fix: #493 Leeds issues

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/EastRidingCouncil.py
> fix: #27 East Riding

- uk_bin_collection/uk_bin_collection/councils/PrestonCityCouncil.py
> fix: #191 Preston City Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/WestLindseyDistrictCouncil.py
> feat: Adding 474 West Lindsey District Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BasingstokeCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BexleyCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BoltonCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BromleyBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/CalderdaleCouncil.py
- uk_bin_collection/uk_bin_collection/councils/CastlepointDistrictCouncil.py
> 191_fixingbroken_councils

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NewportCityCouncil.py
- wiki/Councils.md
* Create NewportCityCouncil
* Update input.json
* Update Councils.md
* Update validate_council_outputs.feature
* Update config_flow.py
> feat: Add Newport City Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/HaringeyCouncil.py
- wiki/Councils.md
Adds scraper for Haringey Council website.
> feat: Add Haringey Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/BrightonandHoveCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ChelmsfordCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LondonBoroughRedbridge.py
> fix: chelmsford #407

- CONTRIBUTING.md
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/SouthOxfordshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ValeofWhiteHorseCouncil.py
Closes #521 to introduce Vale of White Horse Council
This was mostly copied from South Oxfordshire Council's scrapper (as both council use essentially the same site). I've updated both scrapers to handle exceptional schedules (like current bin collection dates, due to bank holidays), as well as an added common function to check if a string contains a date.
> Add Vale of White Horse Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NottinghamCityCouncil.py
> feat: #522 Adding Nottingham City Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BarnetCouncil.py
- wiki/Councils.md
Add in a new scraper for Barnet Council.
The unrelated `councils.md` changes come from running `generate_wiki.py`, so I've left in
> feat: barnet council

- uk_bin_collection/uk_bin_collection/councils/BarnetCouncil.py
Apologies for the multitude of PRs here, in Home Assistant I was getting this error:
```
This error originated from a custom integration.
Logger: custom_components.uk_bin_collection.sensor
Source: helpers/update_coordinator.py:300
Integration: UK Bin Collection Data (documentation, issues)
First occurred: 18:18:42 (1 occurrences)
Last logged: 18:18:42
Unexpected error fetching Home data: time data 'Thursday, 04 January' does not match format '%d/%m/%Y'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/uk_bin_collection/sensor.py", line 129, in _async_update_data
return …
```
> fix: barnet (again)

- uk_bin_collection/uk_bin_collection/councils/ChelmsfordCityCouncil.py
> fix: Update ChelmsfordCityCouncil.py

- uk_bin_collection/uk_bin_collection/councils/KingstonUponThamesCouncil.py
Per https://github.com/robbrad/UKBinCollectionData/issues/545 I found that there were some reliability issues with the existing method of grabbing the data. I switched the code to use Selenium and await the HTMX component loading, which is now very successful (testing locally), albeit a slight delay on invocation.
Supercedes https://github.com/robbrad/UKBinCollectionData/pull/546 as this includes the same fix for holiday date formatting.
> fix: modified Kingston-upon-Thames driver for greater reliability.

- custom_components/uk_bin_collection/config_flow.py
- custom_components/uk_bin_collection/sensor.py
- custom_components/uk_bin_collection/strings.json
- custom_components/uk_bin_collection/translations/en.json
- uk_bin_collection/tests/step_defs/test_validate_council.py
- uk_bin_collection/uk_bin_collection/collect_data.py
> Fix selenium bug #539

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/ChorleyCouncil.py
- wiki/Councils.md
This adds support for Chorley council, closes #371 
Had to add ability to set chrome user agent as Chorley blocks Headless chrome user agent.
_updated to correct commit message format_
> Add support for Chorley Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/TestValleyBoroughCouncil.py
- wiki/Councils.md
Full disclosure, this is a complete copy/paste of Newport City Council as they use the same system. I wonder if there is a way to avoid code reuse like this, as this will be the third version of this same code. 🤔
> Add Test Valley Borough Council

- uk_bin_collection/uk_bin_collection/councils/NorthWestLeicestershire.py
Should be a fix hopefully, hard handle checking for today/tomorrow with an else if.
> Fix for today/tomorrow in North West Leicestershire #581

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NorthYorkshire.py
> feat: Add Support for North Yorkshire Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/CastlepointDistrictCouncil.py
- wiki/Councils.md
For some reason castlepoint was swapped over to selenium in #499 and I can't really work out why.
A single line removed with regards to ssl ciphers fixed the original issue without needing selenium.
> Remove Selenium use from castlepoint

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/StAlbansCityAndDistrictCouncil.py
> feat: Add Scraper for St Albans City and District Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/MoleValleyDistrictCouncil.py
- wiki/Councils.md
> feat: Add Mole Valley District Council

- uk_bin_collection/uk_bin_collection/councils/WestLindseyDistrictCouncil.py
Closes #568.
Also orders collections by date order and uses title casing instead of caps.
> Fix date parsing in West Lindsey District Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/AdurAndWorthingCouncils.py
- uk_bin_collection/uk_bin_collection/councils/BedfordBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/DoverDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HullCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/MansfieldDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/RochfordCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SolihullCouncil.py
- uk_bin_collection/uk_bin_collection/councils/TandridgeDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/TelfordAndWrekinCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WestNorthamptonshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WyreCouncil.py
Closes #552 
Closes #560 
Closes #632 
Closes #625 
Closes #622 
Closes #567 
Closes #621 
Closes #620 
Closes #614 
Closes #544 
Closes #513
> March 2024 additions

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py
- wiki/Councils.md
n.b. only tested on command line and not in HomeAssistant
Fixes #519
> feat: adds Kirklees council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py
- wiki/Councils.md
Apologies, I didn't notice that calendar.aspx?UPRN=XXX ignores the UPRN parameter and just uses the session's address.
> fix: fix Kirklees address search (switch to house & postcode)

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ArunCouncil.py
- wiki/Councils.md
n.b. only tested on command line and not in HomeAssistant
Fixes #624
> feat: add Arun Council

- uk_bin_collection/uk_bin_collection/councils/BroxtoweBoroughCouncil.py
> Fix: #654 - Broxtowe Borough Council parsing error

- uk_bin_collection/uk_bin_collection/councils/BarnetCouncil.py
Closes #660.
- Change how addresses are selected by WebDriver
- Run code formatter
> Fix: #660 - Barnet Council issues

- uk_bin_collection/uk_bin_collection/councils/BCPCouncil.py
> Fix incorrect BCP data

- uk_bin_collection/uk_bin_collection/councils/HaringeyCouncil.py
> fix: Update HaringeyCouncil.py issue #670

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/CheshireWestAndChesterCouncil.py
> feat: Add support for Cheshire West and Chester Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/KnowsleyMBCouncil.py
> feat: add support for Knowsley Metropolitan Borough Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/WestBerkshireCouncil.py
> Add support for West Berkshire Council

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BradfordMDC.py
I've added Bradford Council for bin collections. Used 'Vale of White Horse' council as a base (they seemed to use the same CRM for creating pages).
Currently finds the next collection date and lets you know which bin to put out. Doesn't take into account the subscription option for garden waste, nor does it currently look up the upcoming dates for future collections.
> Added Bradford MDC - closes #442

- uk_bin_collection/uk_bin_collection/councils/BradfordMDC.py
Removed as it's a leftover from testing.
> fix: Remove 'import Dumper'

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/RenfrewshireCouncil.py
feat: Adding Renfrewshire Council
> feat: Adding Renfrewshire Council

- uk_bin_collection/uk_bin_collection/councils/RenfrewshireCouncil.py
fix: Handling the "Website cookies enhance your user experience." button
> fix: Handling the "Website cookies enhance your user experience." button

- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/FarehamBoroughCouncil.py
Adding support for Fareham Borough Council
> feat: Add support for Fareham Borough Council

- CHANGELOG.md
- custom_components/uk_bin_collection/config_flow.py
- custom_components/uk_bin_collection/manifest.json
- pyproject.toml
- uk_bin_collection/tests/features/validate_council_outputs.feature
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/TendringDistrictCouncil.py
> 414 tendring district

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/MoleValleyDistrictCouncil.py
> fix: Update Mole Valley URL

- .devcontainer/docker-compose.yml
- .github/workflows/docker-image.yml
- custom_components/uk_bin_collection/sensor.py
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/BedfordshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BirminghamCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BracknellForestCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BristolCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/CroydonCouncil.py
- uk_bin_collection/uk_bin_collection/councils/DartfordBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/EastCambridgeshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LancasterCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LisburnCastlereaghCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ManchesterCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/NewForestCouncil.py
- uk_bin_collection/uk_bin_collection/councils/NewportCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/NorthTynesideCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SomersetCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SouthCambridgeshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/StHelensBC.py
- uk_bin_collection/uk_bin_collection/councils/StaffordBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SwanseaCouncil.py
- uk_bin_collection/uk_bin_collection/councils/TestValleyBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ThreeRiversDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/UttlesfordDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WaverleyBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WiganBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WindsorAndMaidenheadCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WokingBoroughCouncil.py
Closes #490 
Closes #484 
Closes #503 
Closes #505 
Closes #359
Closes #507 
Closes #425
> Council Pack 2

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BirminghamCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BromleyBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BuckinghamshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HaringeyCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WokingBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WychavonDistrictCouncil.py
> Council pack 3

- .devcontainer/dev.Dockerfile
- .devcontainer/devcontainer.json
- .vscode/launch.json
- custom_components/uk_bin_collection/config_flow.py
- custom_components/uk_bin_collection/sensor.py
- custom_components/uk_bin_collection/strings.json
- custom_components/uk_bin_collection/translations/en.json
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/step_defs/test_validate_council.py
- uk_bin_collection/uk_bin_collection/collect_data.py
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/MidSussexDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ThreeRiversDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
if users dont have a Selenium Server
> feat: adding ability to set local mode in HA custom comp.

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/DorsetCouncil.py
- uk_bin_collection/uk_bin_collection/get_bin_data.py
> Fix: Dorset Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/CornwallCouncil.py
> feature: Add support for Cornwall Council

- uk_bin_collection/uk_bin_collection/councils/BoltonCouncil.py
> fix: #771 Bolton bullet points on dates is now fixed

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BelfastCityCouncil.py
- wiki/Councils.md
Closes https://github.com/robbrad/UKBinCollectionData/issues/523
> Feat: Belfast City Council

- custom_components/uk_bin_collection/__init__.py
> fix: 779 Add correct async wait to Home Assistant

- uk_bin_collection/tests/input.json
- wiki/Councils.md
> fix: 791 Glasgow URL change

- uk_bin_collection/tests/test_collect_data.py
- uk_bin_collection/tests/test_common_functions.py
- uk_bin_collection/tests/test_conftest.py
> fix: #795 unit test coverage

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/RotherhamCouncil.py
👋 Hello, I've added in Rotherham Council, at the minute it only takes in a uprn, however I plan to go back at some point in the future and add postcode support if it's needed, however I believe this to be enough for now.
Cheers!
> feat: added Rotherham Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/IslingtonCouncil.py
> feat: Add IslingtonCouncil

- uk_bin_collection/tests/input.json
See https://github.com/robbrad/UKBinCollectionData/pull/807#issuecomment-2339538156
> chore: Gloucester needs webdriver

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/EalingCouncil.py
> feat: Add Ealing Council

- custom_components/uk_bin_collection/translations/pt.json
Add Portuguese Language 
feat:
> Add Portuguese Language  feat:

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/EastRenfrewshireCouncil.py
> feat: Adding East Renfrewshire Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/WindsorAndMaidenheadCouncil.py
> fix: Windsor and Maidenhead Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ColchesterCityCouncil.py
> feat: Adding Colchester City Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/WinchesterCityCouncil.py
> feat: Adding Winchester City Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BuckinghamshireCouncil.py
> fix: Buckinghamshire Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NeathPortTalbotCouncil.py
> fix: Neath Port Talbot Council

- uk_bin_collection/uk_bin_collection/councils/RochfordCouncil.py
Add strip to clean up data for strptime as would fail otherwise.
> fix: Rochford Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/DacorumBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LondonBoroughLambeth.py
fix: #863 
fix: #559 
fix: #615
> feat: Council Pack 1

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/LondonBoroughEaling.py
> feat: Adding London Borough of Ealing

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ElmbridgeBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HighlandCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SouthDerbyshireDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SouthwarkCouncil.py
fix: #780 
fix: #835 
fix: #842 
fix: #845 
fix: #754
> feat: Council Pack 2

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/FalkirkCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LondonBoroughHarrow.py
- uk_bin_collection/uk_bin_collection/councils/NorthAyrshireCouncil.py
fix: #869 
fix: #871 
fix: #761
> feat: Council Pack 3

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NottinghamCityCouncil.py
> fix: NottinghamCityCouncil

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ArmaghBanbridgeCraigavonCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LichfieldDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WalsallCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WestMorlandAndFurness.py
- uk_bin_collection/uk_bin_collection/councils/WirralCouncil.py
fix: #830 
fix: #870 
fix: #873 
fix: #877 
fix: #602
> feat: Council Pack 4

- uk_bin_collection/uk_bin_collection/councils/MoleValleyDistrictCouncil.py
> fix: MoleValley

- uk_bin_collection/uk_bin_collection/councils/EastRidingCouncil.py
> fix: EastRiding

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/MidlothianCouncil.py
> feat: Add Midlothian Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/AberdeenshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/CanterburyCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LutonBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SwindonBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WestOxfordshireDistrictCouncil.py
- wiki/Councils.md
fix: #900 
fix: #590 
fix: #659 
fix: #694 
fix: #697
> feat: Council Pack 7

- .devcontainer/devcontainer.json
- .github/workflows/behave.yml
- .vscode/launch.json
- Makefile
- conftest.py
- custom_components/uk_bin_collection/config_flow.py
- custom_components/uk_bin_collection/sensor.py
- custom_components/uk_bin_collection/tests/common_utils.py
- custom_components/uk_bin_collection/tests/test_config_flow.py
- custom_components/uk_bin_collection/tests/test_sensor.py
- pyproject.toml
- pytest.ini
- uk_bin_collection/tests/input.json
- uk_bin_collection/tests/step_defs/test_validate_council.py
- uk_bin_collection/uk_bin_collection/councils/ChesterfieldBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/council_class_template/councilclasstemplate.py
fix: #953
fix: #718
fix: #952 
fix: #926 
fix: #774
> fix: CC testing and add Chesterfield

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/GlasgowCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LondonBoroughSutton.py
- uk_bin_collection/uk_bin_collection/councils/MidDevonCouncil.py
- uk_bin_collection/uk_bin_collection/councils/OxfordCityCouncil.py
- wiki/Councils.md
fix: #963 
fix: #962 
fix: #945 
fix: #944
> feat: Council Pack 13

- custom_components/uk_bin_collection/__init__.py
- custom_components/uk_bin_collection/config_flow.py
- custom_components/uk_bin_collection/sensor.py
- custom_components/uk_bin_collection/strings.json
- custom_components/uk_bin_collection/tests/test_config_flow.py
- custom_components/uk_bin_collection/tests/test_sensor.py
- custom_components/uk_bin_collection/translations/cy.json
- custom_components/uk_bin_collection/translations/en.json
- custom_components/uk_bin_collection/translations/ga.json
- custom_components/uk_bin_collection/translations/gd.json
- custom_components/uk_bin_collection/translations/pt.json
**This is a breaking change** 
Fix the no refresh of council and added ability for user to set refresh duration in hours
Fixes #767
> fix: #767 BREAKING CHANGE - RE-ADD your sensors / config

- custom_components/uk_bin_collection/__init__.py
- custom_components/uk_bin_collection/calendar.py
- custom_components/uk_bin_collection/const.py
- custom_components/uk_bin_collection/manifest.json
- custom_components/uk_bin_collection/sensor.py
- custom_components/uk_bin_collection/tests/test_calendar.py
Adding a calendar type to allow people caldendar entries as well as sensor
> feat: adding calendar for Bins in Custom Component

- uk_bin_collection/uk_bin_collection/councils/NuneatonBedworthBoroughCouncil.py
- wiki/Councils.md
Date format correction for Nuneaton and Bedworth Borough Council
> fix: NBBC Date Fix

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/AntrimAndNewtonabbeyCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BradfordMDC.py
- uk_bin_collection/uk_bin_collection/councils/BroxbourneCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HertsmereBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WarringtonBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WestLancashireBoroughCouncil.py
- wiki/Councils.md
fix: #984
fix: #982 
fix: #980 
fix: #776
fix: #969 
fix: #695
> fix: Council Pack 14

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/AberdeenCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BraintreeDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/BurnleyBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/EdinburghCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/ExeterCityCouncil.py
- wiki/Councils.md
fix: #1019 
fix: #894 
Edinrbugh is similar to Babergh Council in that the local authority only provides PDF collection schedules that are difficult to parse.
Instead, I have attempted to predict the correct schedule based on being provided the DAY and WEEK or collection, i.e. Thursday/Week2
fix: #1017 
fix: #1015 
fix: #699
> feat: Council Pack 17

- uk_bin_collection/uk_bin_collection/councils/BroxbourneCouncil.py
I noticed that my council (Broxbourne) integration was crashing when parsing bin collection data. The issue was caused by the addition of optional green waste collections, which sometimes result in empty strings being provided for collection dates. This caused the parser to crash when attempting to format an empty string as a date.
This PR fixes the issue by skipping rows with empty or invalid collection dates, ensuring only valid data is processed and preventing the crash.
> fix: prevent crash when parsing invalid or empty date strings (Broxbourne)

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BlaenauGwentCountyBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LondonBoroughSutton.py
- uk_bin_collection/uk_bin_collection/councils/MertonCouncil.py
- uk_bin_collection/uk_bin_collection/councils/RedditchBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SalfordCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SwaleBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WandsworthCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WiltshireCouncil.py
- wiki/Councils.md
fix: #1097 - Salford City Council
fix: #1094 - Wiltshire Council
fix: #1098 - Blaenau Gwent County Borough Council
fix: #1068 - Redditch Borough Council
fix: #1076 - London Borough Sutton
fix: #1080 - Swale Borough Council
fix: #1078 - Adding Wandsworth Council
> feat: Council Pack 21

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/SurreyHeathBoroughCouncil.py
Added Surrey Heath Borough Council.
> Feat: Add Surrey Heath Borough Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/MedwayCouncil.py
Implements Medway Council (closes #1021)
> feat: implement Medway Council (#1021)

- uk_bin_collection/uk_bin_collection/councils/MertonCouncil.py
Added garden waste, skips if not subscribed to avoid breaking the date logic below. Closes #1172.
> fix: Add garden waste to Merton Council

- .gitignore
- README.md
- custom_components/services.yaml
- custom_components/uk_bin_collection/README.md
- custom_components/uk_bin_collection/__init__.py
- custom_components/uk_bin_collection/calendar.py
- custom_components/uk_bin_collection/config_flow.py
- custom_components/uk_bin_collection/const.py
- custom_components/uk_bin_collection/services.yaml
- custom_components/uk_bin_collection/strings.json
- custom_components/uk_bin_collection/tests/common_utils.py
- custom_components/uk_bin_collection/tests/test_calendar.py
- custom_components/uk_bin_collection/tests/test_config_flow.py
- custom_components/uk_bin_collection/tests/test_init.py
- custom_components/uk_bin_collection/tests/test_sensor.py
- custom_components/uk_bin_collection/translations/cy.json
- custom_components/uk_bin_collection/translations/en.json
- custom_components/uk_bin_collection/translations/ga.json
- custom_components/uk_bin_collection/translations/gd.json
- custom_components/uk_bin_collection/translations/pt.json
- uk_bin_collection/uk_bin_collection/councils/AberdeenCityCouncil.py
- wiki/Home.md
> Feat add manual refresh control

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/IpswichBoroughCouncil.py
Council request https://github.com/robbrad/UKBinCollectionData/issues/920
fix: #920
> feat: Adding Ipswich Borough Council

- uk_bin_collection/tests/input.json
> fix: 1232 East herts missing Selenium url in input.json

- uk_bin_collection/tests/input.json
> fix: 1235 Councils missing Selenium in input.json

- uk_bin_collection/tests/check_selenium_url_in_input.json.py
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/GloucesterCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/MiddlesbroughCouncil.py
adding #833 Middlesbrough 
adding selenium check script uk_bin_collection/tests/check_selenium_url_in_input.json.py this helps check that there is a Selenium url in the input.json
> Council_pack_5

- uk_bin_collection/uk_bin_collection/councils/NorthYorkshire.py
On the North Yorkshire Council website, it's possible for multiple bins to be on the same day (see image below, where the Garden Waste and Household Waste come on the same day):
This causes the data to come back as follows:
```json
{
"bins": [
{
"type": "Recycling - brown bin",
"collectionDate": "19/02/2025"
},
{
"type": "Household waste",
"collectionDate": "26/02/2025"
},
{
"type": "Recycling - blue bin",
"collectionDate": "05/03/2025"
},
{
"type": "Garden waste \n \n                    Household waste",
"collectionDate": "12/03/2025"
},
{
"type": "Recycling - brown bin",
"collectionDate": "19/03/2025"
},
{
"type": "Garden waste \n \n                    Household waste",
"collectionDate": "26/03/2025"
},
{
"type": "Recycling - blue bin",
"collectionDate": "02/04/2025"
},
{
"type": …
```
> fix: North Yorkshire - multiple bins on a day

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/CambridgeCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/CanterburyCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/CastlepointDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HackneyCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HinckleyandBosworthBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SouthamptonCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SpelthorneBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WakefieldCityCouncil.py
- wiki/Councils.md
**Fixing the following councils**
fix: #1254 - Canterbury City Council
fix: #1252 - Castlepoint District Council
fix: #1230 - Hackney Council
fix: #1267 
fix: #1207 - Hinckley and Bosworth Borough Council
fix: #1256 - Bexley Council
**Adding the following councils**
fix: #1270 - Spelthorne Borough Council
fix: #1264 - Cambridge City Council
fix: #1057 - Southampton City Council
**Already fixed issues to be closed**
fix: #1188
> fix: 2025 Council Pack 6

- uk_bin_collection/uk_bin_collection/councils/WalthamForest.py
> fix: Waltham Forest council

- wiki/Councils.md
As per this discussion.
https://github.com/robbrad/UKBinCollectionData/pull/1261
> Update Councils.md to revise Brighton and Hove

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/FyldeCouncil.py
- uk_bin_collection/uk_bin_collection/councils/GloucesterCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HastingsBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/MidDevonCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WestOxfordshireDistrictCouncil.py
- wiki/Councils.md
**Fixing the following councils**
fix: #1290 - West Oxfordshire Council
fix: #1277 fix: #1287 - Mid Devon Council
fix: #1282 - Gloucester City Council
**Adding the following councils**
fix: #1039 fix: #1181 fix: #1266 fix: #1274 - Fylde Council
fix: #1249 - Hastings Borough Council
**Already fixed issues to be closed**
fix: #1215 fix: #1225 - The fix for this issue is to ensure that "Automatically refresh the sensor" is ticked within your configuration
> fix: 2025 Council Pack 7

- uk_bin_collection/uk_bin_collection/councils/WalthamForest.py
Reverting PR #1280 
They went back to how it was before, so the previous code works fine now.
> fix: Waltham forest council - revert previous changes

- .gitignore
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BroadlandDistrictCouncil.py
Added Broadland District Council. This uses Selenium.
As per [this request](https://github.com/robbrad/UKBinCollectionData/issues/1276).
> feature: Added Broadland District Council (retry)

- uk_bin_collection/tests/input.json
> fix: Newham council

- custom_components/uk_bin_collection/__init__.py
- custom_components/uk_bin_collection/tests/test_init.py
> fix: #1304 - sesnors goes to unknown if the data is blank from council is who are less reliable

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/StirlingCouncil.py
As per [this request](https://github.com/robbrad/UKBinCollectionData/issues/1253).
> feat: Added Stirling Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BarkingDagenham.py
As per [this request](https://github.com/robbrad/UKBinCollectionData/issues/1227).
closes: #1227
> feat: Added Barking & Dagenham

- uk_bin_collection/uk_bin_collection/councils/AshfordBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/EastHertsCouncil.py
- uk_bin_collection/uk_bin_collection/councils/HertsmereBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/LeedsCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/WindsorAndMaidenheadCouncil.py
> fix: #1301 Fix Leeds Council

- uk_bin_collection/tests/input.json
> fix: Google Cal

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/RenfrewshireCouncil.py
> fix: Renfrewshire Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/GreatYarmouthBoroughCouncil.py
> feat: added Great Yarmouth

- .vscode/launch.json
- pytest.ini
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/common.py
- uk_bin_collection/uk_bin_collection/councils/KnowsleyMBCouncil.py
- uk_bin_collection/uk_bin_collection/councils/MidUlsterDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SandwellBoroughCouncil.py
> council pack

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/Hillingdon.py
As per [this request](https://github.com/robbrad/UKBinCollectionData/issues/1047).
https://www.hillingdon.gov.uk/collection-day
UB10 8PP
This is an unusual format. The output seems hand written rather than generated from a database, so the scraper might break in the future.
Navigation via Selenium is straightforward but the collection dates are in the form of _Every Tuesday_ and then you need to check a bank holiday changes page found [here](https://www.hillingdon.gov.uk/bank-holiday-collections).
> Added Hillingdon

- uk_bin_collection/uk_bin_collection/councils/Hillingdon.py
Wanted to ensure it would work even if the bank holiday URL was missing.
> fix: more robust bank holiday handling for Hillingdon

- uk_bin_collection/uk_bin_collection/councils/CheltenhamBoroughCouncil.py
I've made a first attempt to address #1362 namely updating collection dates if there's a bank holiday.
I probably could've/should've used the is_holiday function.. but checking if a date is in a dictionary seemed reasonable.
More than happy to be told I've gone about this all wrong, this is a faaar more complex integration than I've contributed to before 🙃
> fix: Chelts - Add bank holiday data

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/MorayCouncil.py
Fixes this
https://github.com/robbrad/UKBinCollectionData/issues/1377
> fix: processed all bins for Moray

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/MeltonBoroughCouncil.py
As per https://github.com/robbrad/UKBinCollectionData/issues/1380
Didn't require Selenium after all.
> feat: added Melton

- uk_bin_collection/tests/input.json
Fixes this
https://github.com/robbrad/UKBinCollectionData/issues/1375
The script didn't use Selenium but input.json was asking for it.
> fix: simplified blackburn

- uk_bin_collection/uk_bin_collection/councils/BrentCouncil.py
specifically handling "(this collection has been adjusted from its usual time)"
> fix: more robust brent date handling

- uk_bin_collection/tests/input.json
To avoid some confusion as per this post.
https://github.com/robbrad/UKBinCollectionData/issues/1392
> fix: added skip_get_url to hyndburn

- uk_bin_collection/uk_bin_collection/councils/NorthEastDerbyshireDistrictCouncil.py
Fixes https://github.com/robbrad/UKBinCollectionData/issues/1391
> fix: North East Derbyshire - all bins

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/ChichesterDistrictCouncil.py
Also, it was timing out so tried to make it more robust.
> fix: Chichester now only requires postcode and house number

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/TewkesburyBoroughCouncil.py
Easy one. Just needs UPRN. No Selenium.
> feat: Added Tewkesbury Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/FermanaghOmaghDistrictCouncil.py
As per this request https://github.com/robbrad/UKBinCollectionData/issues/1200
> feat: Added Fermanagh Omagh Council

- uk_bin_collection/uk_bin_collection/councils/StokeOnTrentCityCouncil.py
Fixes https://github.com/robbrad/UKBinCollectionData/issues/1411
> fix: Stoke date-time fix

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/GuildfordCouncil.py
- uk_bin_collection/uk_bin_collection/councils/MaidstoneBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/TorbayCouncil.py
Fixes https://github.com/robbrad/UKBinCollectionData/issues/1416.
Also fixed Maidstone and a small change to Guildford.
> Council fixes

- uk_bin_collection/uk_bin_collection/councils/SouthRibbleCouncil.py
- wiki/Councils.md
Added Fixes for South Ribble Council, this uses Jadu, which is the same as Birmingham City council.
there are two forms, one is 70 which is for South Ribble Council, and the other is 71 which is for Chorley. i have only fixed my council currently.
Test Postcode is PR26 7RZ
> Fixed South Ribble Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/EastleighBoroughCouncil.py
Fixes https://github.com/robbrad/UKBinCollectionData/issues/1428 by using Selenium.
> fix: Eastleigh cloudflare fix

- uk_bin_collection/uk_bin_collection/councils/NorthumberlandCouncil.py
to address this
https://github.com/robbrad/UKBinCollectionData/issues/1430
> fix: more robust Northumberland

- uk_bin_collection/uk_bin_collection/councils/NorthSomersetCouncil.py
North Somerset are moving to 3-weekly collections, and currently the website has a blank cell in the "Following collection date" column.  Added checking to ignore that column if empty.
The code will work as before if/when the column is populated again.
> Update to fix North Somerset

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/AdurAndWorthingCouncils.py
- uk_bin_collection/uk_bin_collection/councils/BradfordMDC.py
- uk_bin_collection/uk_bin_collection/councils/EastleighBoroughCouncil.py
- uk_bin_collection/uk_bin_collection/councils/NorthHertfordshireDistrictCouncil.py
Created a new script for North Hertfordshire - https://github.com/robbrad/UKBinCollectionData/issues/1435
Fixed Adur, since it had stopped working - (not reported)
Removed the duplicate entries in Bradford - https://github.com/robbrad/UKBinCollectionData/issues/1436
Fixed an intermittent date fault with Eastleigh - https://github.com/robbrad/UKBinCollectionData/issues/1446
Added postcode for South Ribble but still needs full fix - https://github.com/robbrad/UKBinCollectionData/issues/1407
> Council fixes (05 21)

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/SouthRibbleCouncil.py
Reworked South Ribble, i have tested and it works can confirm the token is captured correctly
There is no need for selenium, and I updated all files as i made a mistake in the last PR as i was rushing out the door to go on holiday, this should now close the outstanding issues with this council not working.
> fix(SouthRibble): Resolved South Ribble without selenium

- custom_components/uk_bin_collection/config_flow.py
- custom_components/uk_bin_collection/const.py
- pyproject.toml
- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/SouthRibbleCouncil.py
ref: #1464 South Ribble
ref: #1407
> fix: South Ribble and version pinning issues for input.json

- uk_bin_collection/uk_bin_collection/councils/WestOxfordshireDistrictCouncil.py
Website seems to have altered the reference to the combo box which is now combobox-input-23
> Fix West Oxfordshire Council

- uk_bin_collection/uk_bin_collection/councils/MidlothianCouncil.py
Add request headers to fix the following issue:
#1522
> Fix Midlothian Council - Add request headers to resolve 403 Forbidden

- uk_bin_collection/uk_bin_collection/councils/SwindonBoroughCouncil.py
Fixes #1503 as a 403 error was returned with the default user agent
> fix: Add headers to request for Swindon Borough Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BroxbourneCouncil.py
- uk_bin_collection/uk_bin_collection/councils/EastHertsCouncil.py
- uk_bin_collection/uk_bin_collection/councils/EastLothianCouncil.py
- uk_bin_collection/uk_bin_collection/councils/EastRenfrewshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/EnfieldCouncil.py
- uk_bin_collection/uk_bin_collection/councils/FermanaghOmaghDistrictCouncil.py
- uk_bin_collection/uk_bin_collection/councils/GatesheadCouncil.py
> July Part 2 : Multiple council fixes

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/DarlingtonBoroughCouncil.py
Add support for Darlington Borough Council
> Add support for Darlington Borough Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/BoltonCouncil.py
- wiki/Councils.md
Update URL fopr Bolton council
Fixes 1573
> fix: 1573 Update Bolton council URL

- uk_bin_collection/uk_bin_collection/councils/SandwellBoroughCouncil.py
Sandwell have updated their bin schedule. This PR is meant to fix it with the new IDs
> chore: Update SandwellBoroughCouncil lookups

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/EastDunbartonshireCouncil.py
- uk_bin_collection/uk_bin_collection/councils/NewportCityCouncil.py
- uk_bin_collection/uk_bin_collection/councils/SomersetCouncil.py
- uk_bin_collection/uk_bin_collection/councils/TestValleyBoroughCouncil.py
- wiki/Councils.md
**New Councils**
fix: #1557 - Adding East Dunbartonshire
**BREAKING FIXES**
fix: #1574 - Test Valley Borough Council - NOTE: This now requires Selenium
fix: #1559 - Newport City Council - NOTE: This now requires Selenium
fix: #1569 - Somerset Council - NOTE: This now requires Selenium
_Not fixed by this PR but tagging to close the issues_
fix: #1561 - Cheltenham
fix: #1596 - Northumberland County council
fix: #1598
fix: #1573
fix: #1558
fix: #1522 
fix: #1446 - Fixed in #1515
fix: #1428 - Fixed in #1515
fix: ##1247 - Fixed in #1415 
fix: #1377  - Fixed in #1383 
fix: #1239 - Fixed in #1412 
fix: #1391 - Fixed in #1412
fix: #1392 - Fixed in #1412
fix: #1200 - Fixed in #1412
fix: #1397 - Fixed in #1412
fix: #1411 - Fixed in #1414
fix: #1416 - Fixed in #1417
fix: #1434 - Fixed in#1422
fix: …
> fix: Council Fix Pack - October 2025

- uk_bin_collection/uk_bin_collection/councils/MidSuffolkDistrictCouncil.py
- Replace static bank holiday list with dynamic `holidays.UK()` library
- Implement smart date calculation that handles weekends and cascading holidays
- Add configurable delays for major holidays (Christmas/New Year get 2-day delays)
- Simplify garden collection logic with Christmas period detection
- Automatic holiday detection for future years
- More robust handling of edge cases
- Cleaner, more maintainable code
- No manual holiday updates required
Fixes issues with hardcoded holiday dates that would become outdated.
>   fix: replace hardcoded holidays with dynamic detection for Mid Suffolk District Council

- uk_bin_collection/tests/input.json
- uk_bin_collection/uk_bin_collection/councils/NewForestCouncil.py
Fixes #1521
Update for wheelie bins and new page layout. Falls back to old way if it would tell you that you're in a later phase. Should be future proof and once March 2026 comes around, we should be able to remove the "legacy" code.
> fix: Fix New Forest Council
